문자열 계산기 기본 구현 초안
programmers-lecture/java-calculator pull request #10
Opened 2022-11-06 09:38 UTC by zeze1004

### 기본 로직
- 문자열 입력 
- 공백 기준으로 문자열 입력을 list로 변경
- 연산자는 홀수일 때만 나타나므로 홀수 조건문으로 연산자 찾음
- 첫 연산자는 앞뒤 정수들과 계산시킴
- 두번째 연산자부터는 첫 연산자 때 계산한 값(`result`)과 연산자 다음에 나오는 정수와 계산시킴

### 질문
우선순위 구현 전에 과제 방향성 질문을 위해 먼저 pr 올립니다!
강의 주제가 `stream`과 `option` 이었는데, 해당 주제를 이번 과제에 사용해야하나요?
이런 식(?)으로 구현을 해도 되는지 확신이 없어서 문의드립니다.
핳 제 코드가 부끄럽네요.

2022-11-06 09:52 UTC, SeokRae reviewed
안녕하세요. zeze님! 코드리뷰를 진행할 "알" 입니다.

과제 진행에 고생하셨습니다.!

> 강의 주제가 stream과 option 이었는데, 해당 주제를 이번 과제에 사용해야하나요?

첫 주차의 과제 목표는 자바라는 언어에 친숙해지는 것과, 
몇 가지 요구사항을 자신이 알고 있는 문법, 객체지향 프로그래밍 언어라는 도구로 구현해보는 것을 목표로 하고 있습니다.

stream, optional 과 같은 문법들은 구현하는 방식에 따라 사용이 될 수도 있고, 사용되지 않을 수도 있습니다.

1주차의 과제는 반복문과 조건문 만으로도 구현이 가능한 과제이므로 1차적으로 가장 간단하게 작성하고, 이를 리펙토링하여 발전시키는 과정을 통해 학습하시면 좋을 것 같습니다. 

리뷰는 가장 기본적인 부분(문법) 부터 객체지향을 위한 본질적인 내용, 코드에 대한 검증 방법 등으로 진행할 예정입니다.

---

먼저 크게는 문자열 계산기라는 프로그램을 요구사항을 충족하여 무작위 다수에게 제공한다고 생각해보시면 좋을 것 같습니다. 그리고 몇 가지 관점에서 프로그램을 바라보고 개선될 여지는 없는지, 한 번 확인해보시면 좋겠네요.

1. 사용자가 프로그램을 실행하면 문자열 계산기라는 서비스를 사용할 수 있을까?
2. 개발자의 입장에서 프로그램에 대해 추가적인 요구사항 및 수정이 필요한 경우, 이를 보다 쉽게 분석할 수 있도록 만들기 위해서는 어떻게 해야 할까?
3. 요구사항을 설계한 프로그램은 자바 프로그래밍 언어의 특성이나 원칙 등을 활용한 방식으로 작성이 되었을까?

---

현 상황에서 말씀드리고 싶은 리펙토링 방향은 아래 세 가지 내용을 클래스로 분리해보는 것을 추천드립니다.

1. 사용자의 입력
2. 입력 받은 값들의 연산
3. 연산된 결과를 사용자에게 다시 출력

<img width="450" alt="CleanShot 2022-11-06 at 18 44 58@2x" src="https://user-images.githubusercontent.com/17922700/200164058-4136202e-ac7a-47f5-9701-0c90e0b036bd.png">


그 후에 연산이라는 내용은 추상적이고, 더하기 / 빼기 / 곱하기 / 나누기에 대한 구체적인 내용을 어떻게 구성할 수 있을까 고민해보시면 좋을 듯합니다.

<img width="569" alt="CleanShot 2022-11-06 at 18 50 22@2x" src="https://user-images.githubusercontent.com/17922700/200164251-3b7f4b8e-a9e4-4f5c-b554-03c0506424d0.png">

2022-11-06 09:52 UTC, SeokRae commented on src/main/java/Calculator.java
> +        ArrayList<String>  operations = new ArrayList<>(Arrays.asList(operationArray));
```suggestion
        List<String>  operations = new ArrayList<>(Arrays.asList(operationArray));
```

사용하지 않는 필드는 삭제해도 좋을 것 같군요.!
사용하지는 않지만 선언 및 초기화된 내용에 대해서 공유드릴 만한 내용이 있어서 짧은 설명과 관련된 링크 남깁니다.

자바는 인터페이스와 그를 구현한 구현체들이 존재합니다. 
[참고 - Collections in Java](https://www.javatpoint.com/collections-in-java)

컬렉션을 사용하는 방식은 공통적인 api인 입력, 조회, 수정, 삭제 등을 사용하고 상황에 따라 필요한 방식에 따라 적합한 자료구조를 선정하게 됩니다. 
그리하여 선언은 인터페이스(List)를 선언하고, 그에 따라 필요한 구현체(ArrayList)를 선언하는 방식으로 사용합니다. 

그리고 이펙티브 자바라는 책에서는 인터페이스를 타입으로 사용하는 습관을 길러 프로그램을 유연하게 사용하라는 내용이 있어 공유드립니다.

> "적합한 인터페이스만 있다면 매개변수뿐 아니라 반환값, 변수, 필드를 전부 인터페이스 타입으로 선언하라"

[이펙티브 자바 - 아이템 64 객체는 인터페이스를 사용해 참조하라](https://github.com/Meet-Coder-Study/book-effective-java/blob/main/9장/64_객체는_인터페이스를_사용해_참조하라_김재준.md)

2022-11-07 01:00 UTC, ksy90101 commented on src/main/java/Calculator.java
> +                    result += Integer.parseInt(splitInput[i - 1]) * Integer.parseInt(splitInput[i + 1]);
이런식으로 하기 보단, 객체 분리를 해보면 어떨까 합니다.
일단 Operator만 먼저 진행해보면 좋을듯 한데요.
아래 글을 한번 참고해서 진행해보시면 어떨까요?
https://rutgo-letsgo.tistory.com/167

2022-11-07 01:00 UTC, ksy90101 commented on src/main/java/Calculator.java
> +        String input = sc.nextLine();
View는 객체로 분리해보면 어떨까요?
실제 View를 받는 객체를 만들어 주세요.

2022-11-07 01:00 UTC, ksy90101 requested changes
안녕하세요!
간단한 피드백을 남기긴 했지만, 설계의 초안을 제공해드린것이라 2개만 남기고 글을 참고해서 한번 해보세요~
질문이 잇다면 언제든 LMS에 올려주시면 답변 드리겠습니다!

2022-11-09 12:02 UTC, zeze1004 commented
@SeokRae @ksy90101 정성스러운 리뷰 감사합니다
하나씩 수정해보겠습니다!

2022-11-09 12:17 UTC, zeze1004 commented on src/main/java/Calculator.java
> +        ArrayList<String>  operations = new ArrayList<>(Arrays.asList(operationArray));
앗 감사합니다 
처음에 리스트 방식으로 할려다가 문자열 분리(split) 방식으로 바꾼 후 구문 삭제하는걸 깜박했어요,,,! 

+) 인터페이스 개념이 아직 낯설어서,,,아래 객체 분리 리뷰대로 적용해보고 도전해보겠습니다~!

2022-11-12 11:26 UTC, zeze1004 commented on src/main/java/Calculator.java
> +        String input = sc.nextLine();
리뷰 주신대로 view 객체 분리해봤어요! java에서 MVC 패턴이 국룰패턴(?)으로 알고 있어서 model이랑 controller도 만들려고 했으나...일단 view만 구현해봤습니다...^ㅁ^

2022-11-13 13:41 UTC, SeokRae commented on src/main/java/calculator/calculator.java
> +        }
입 출력 관련 기능을 별도의 클래스로 분리하여 나누셨군요.!

도메인 관련된 내용을 구현할 때는 처음에는 "1 + 1" 처럼 한 번만 연산 하는 로직을 먼저 구현해보시면 좋을 듯합니다.
그 후에 반복하여 연산이 이루어 지도록 확장할 수 있을 것 같습니다.

알고리즘을 참고해보시는 것도 좋습니다.
[224. Basic Calculator](https://leetcode.com/problems/basic-calculator/)

2022-12-04 12:03 UTC, merged