[2기][정태현] 문자열 계산기 과제
programmers-lecture/java-calculator pull request #12
Opened 2022-11-16 07:44 UTC by alweiis

필수 요구사항, 추가 요구사항, 미션 가이드를 모두 생각하면서 구현하려고 하니 머릿속이 복잡해져서 코드를 작성하는 것을 계속 미루게 됐습니다...
LMS에서 피드백 주신 내용대로 일단 제가 생각나는 방향대로만 간단하게 구현해보았고, 피드백을 받고 리팩토링을 진행해보겠습니다.

제가 구현한 코드는 사용자로부터 한 줄의 문자열을 입력받지만, 피연산자 2개와 연산자 1개를 입력받고, 계산을 1번만 진행하는 상황으로 가정하고 코드를 작성했습니다. 
여러 예외사항들(ex. 연산자가 없이 입력이 된 경우, 연산자가 연속해서 입력되는 경우)이 떠올랐지만 이런 부분까지 생각하고 작성하려니까 진행이 잘 안되서 일단 간단하게만 구현해보았습니다. 제가 작성한 코드에서 어떤 방향을 먼저 고려해서 리팩토링을 진행할지 알려주시면 그 방향대로 수정해보겠습니다. 감사합니다!

2022-11-16 15:44 UTC, SeokRae reviewed
안녕하세요. 태현님!

![CleanShot 2022-11-16 at 23 52 18](https://user-images.githubusercontent.com/17922700/202213819-23656de3-8f47-400d-a479-079e159e5937.png)

고민하고 계신 
두 세트 이상의 연산자와 피 연산자로 인한 두 차례이상 연산이 필요한 경우의 `알고리즘`, 
연산자와 피 연산자 그리고 실제 연산처리를 진행하는 `책임의 분리`, 
서비스에서 처리할 수 있는 것과는 별개로 사용자의 무분별한 입력에 대한 `예외처리` 
등은 어떤 서비스에도 존재하는 내용으로 생각하기는 쉽지만 구현하는 것은 많은 고민이 필요한 부분이 맞습니다.

우선 한 차례 연산을 진행하는 로직을 처리하는 것부터 시작하신 방법도 좋습니다.
최소한이라도 작성하신 코드가 있어야 이를 기반으로 반복적인 연산을 어떻게 할 수 있을까 고민할 수 있기 때문입니다.

현재 코드에서 가장 부담없이 변경이 가능한 부분은 calculate라는 메서드가 가장 유력해보입니다.

Calculator라는 클래스 내에 start()라고 해서 콘솔의 시작과 끝을 담당하는 것으로 보이고
calculate()메서드의 경우에는 순수 함수로 파라미터를 기준으로 연산처리만 진행하니
이를 별도의 클래스로 분리하여 연산자를 관리, 특정 연산자의 연산처리를 담당하게끔 구성할 수 있을 것 같습니다.

이를 우선적으로 고민해보신 후에 한 차례 입력으로 끝나는 연산을 반복적으로 처리할 수 있는 방법에 대해서 고민해보시는 것을 권장합니다.

화이팅입니다.!

2022-11-16 15:44 UTC, SeokRae commented on src/main/java/view/InputView.java
> +    public static String read() {
static 메서드를 제공하는 클래스의 경우에는 클라이언트 클래스에서 new 라는 키워드를 통해 객체를 생성하지 않아도 되기 때문에
불필요한 객체 생성을 방지하기 위해 private 생성자를 명시하는 것을 권장합니다.

2022-11-16 15:44 UTC, SeokRae commented on src/main/java/view/OutputView.java
> +public class OutputView {
InputView의 private 생성자 내용과 같습니다.

2022-11-16 15:44 UTC, SeokRae commented on src/main/java/controller/Calculator.java
> +    private Integer calculate(int number1, int number2, char operator) {
명확하게 입력된 연산자에 대한 연산처리를 진행하는 메서드군요.!
number1, number2라는 변수명을 사용하는 것보다는 피 연산자를 구별할 수 있는 변수명으로 수정하는 것이 좋아보입니다.

2022-11-20 07:44 UTC, ksy90101 commented on src/main/java/controller/Calculator.java
> +        Queue<Character> queue = new LinkedList<>();
Queue보단, Deque를 써보면 어떨까요?
아래 링크를 참고해보세요.

https://tecoble.techcourse.co.kr/post/2021-05-10-stack-vs-deque/

2022-11-20 07:44 UTC, ksy90101 commented on src/main/java/controller/Calculator.java
> +    private Integer calculate(int number1, int number2, char operator) {
한번 해당 부분을 enum으로 OCP에 용이하도록 해보면 어떨까요?

https://rutgo-letsgo.tistory.com/167

위 글을 한번 참고해보세요 :)

2022-11-20 07:45 UTC, ksy90101 requested changes
간단한, 구조 변경에 대한 피드백을 남겨봤습니다.
참고해서 수정해주시면 감사하겠습니다.
질문은 언제든지 환영입니다.

2022-12-04 12:04 UTC, merged