[1주차][S-ryuri] 자바 문자열 계산기
programmers-lecture/java-calculator pull request #16
Opened 2022-12-06 16:12 UTC by s-ryuri

안녕하세요. 
자바 문자열 계산기 PR 올립니다.

## QnA
<img width="614" alt="image" src="https://user-images.githubusercontent.com/66999675/205962510-18160fdf-b360-4eaa-86f5-8bb1190e4824.png">
- 원래는 plus, minus, multiply, divide를 Main class쪽에서 사용해서 의미를 더 명확하게 나타내고 싶었는데 이렇게 하려면 If 문을 4개나 사용해야할 것 같아서 caculate로 한 번에 처리했습니다.
- 이렇게 한 번에(?) 처리를 하는 로직보단 의미 있는 이름을 가지는 메서드로 분리하는 게 더 나을까요??
- 또한 caculate에 If문 4개가 있는데 이것또한 메서드로 추출을 하던가 아니면 다른 방식으로 해서 추상화를 진행하는 게 더 괜찮을까요??

2022-12-07 15:00 UTC, ksy90101 commented on src/main/java/Calculator.java
> +    //아니면 plus, minus처럼 의미를 명시해주는 게 나을까?
주석은 고민이 끝나면 삭제해주시는게 좋을듯 합니다 :)

2022-12-07 15:01 UTC, ksy90101 commented on src/main/java/Calculator.java
> +    }
View와 관련된 코드는 View라는 Class를 두고 MVC와 같이 변경해보면 어떨까요?

2022-12-07 15:01 UTC, ksy90101 commented on src/main/java/Calculator.java
> +        for (final String s : formula) {
s라는 단어보단 더 의미있는 단어를 사용해보시면 어떠세요?

2022-12-07 15:02 UTC, ksy90101 commented on src/main/java/Calculator.java
> +    }
addNumber라면 인자도 number가 되어야 하지 않을까요?

2022-12-07 15:02 UTC, ksy90101 commented on src/main/java/Calculator.java
> +        return divide(firstNum, secondNum);
이 부분을 우린 한번.
https://rutgo-letsgo.tistory.com/167
Enum을 이용해 전략패턴을 사용해보면 어떨까요?

2022-12-07 15:06 UTC, ksy90101 commented on src/main/java/Number.java
> +
```suggestion
    }
    
    public boolean sameSize(int size) {
        return this.size() == size;
    }

```

개행도 클린코드를 위해 의미를 나타내긴 합니다. 개행도 신경써주세요.

2022-12-07 15:07 UTC, ksy90101 commented on src/main/java/Number.java
> +public class Number {
원시값 포장 👍 
그러나 이름을 보면 Number만 있을거 같은데 Number의 Collections이 있네요? 그렇다면 이런 경우엔 Numbers라는 단어가 어울릴듯 한데 어떻게 생각하시나요?

2022-12-07 15:07 UTC, ksy90101 commented on src/main/java/Symbol.java
> +        return Arrays.asList("+", "-", "*", "/").contains(symbol);
"+", "-"... 이 4개는 위에서 제안드린 Enum방식으로 변경해보시면 이 코드가 사라질수도 있겟네요?

2022-12-07 15:08 UTC, ksy90101 requested changes
안녕하세요 :) 강사 겸 리뷰어 마르코입니다.
전체적으로 잘 구현해주셨네요 💯 
어느정도 클래스 분리를 해주신것에 좋은 시도라고 생각합니다.
간단한 피드백을 남겼으니 한번 참고해보세요~

2022-12-07 17:42 UTC, s-ryuri commented on src/main/java/Calculator.java
> +    //아니면 plus, minus처럼 의미를 명시해주는 게 나을까?
넵, 삭제하도록 하겠습니다

2022-12-07 17:42 UTC, s-ryuri commented on src/main/java/Calculator.java
> +    }
한 번 고민해보고 수정해보도록 하겠습니다.

2022-12-07 17:42 UTC, s-ryuri commented on src/main/java/Calculator.java
> +        for (final String s : formula) {
자동완성 된 걸로 바로 사용해버렸네요,,
생각해보고 수정하겠습니다.

2022-12-07 17:43 UTC, s-ryuri commented on src/main/java/Calculator.java
> +    }
아 Number Class가 있으니 인자도 Number로 들어가는 게 맞겠군요
숫자를 의미해서 Number로 썼는데 겹쳐버렸네요
한 번 고민해보겠습니다.

2022-12-07 17:44 UTC, s-ryuri commented on src/main/java/Calculator.java
> +        return divide(firstNum, secondNum);
오호.. 전략패턴을 사용할 수 있군요
참고해서 해보고 궁금한 사항 질문드리겠습니다.

2022-12-07 17:44 UTC, s-ryuri commented on src/main/java/Number.java
> +
넵

2022-12-07 17:44 UTC, s-ryuri commented on src/main/java/Number.java
> +public class Number {
List가 있기에 list를 나타낼 수 있는 Numbers가 더 적합할 것 같네요
수정하도록 하겠습니다.

2022-12-07 17:45 UTC, s-ryuri commented on src/main/java/Symbol.java
> +        return Arrays.asList("+", "-", "*", "/").contains(symbol);
전략 패턴 적용해보고 수정해보도록 하겠습니다.

2022-12-20 14:49 UTC, ksy90101 commented on src/main/java/Calculator.java
> +    }
이 부분이 enum에 구현되어 있는데 중복된거 같아요.

2022-12-30 04:17 UTC, merged