곱하기 , 나누기 연산식 완료
programmers-lecture/java-calculator pull request #19
Opened 2022-12-08 01:15 UTC by s2s22

더하기 ,빼기는 다른 방법 고민중...

2022-12-08 02:40 UTC, Jo-GyuHyeon requested changes
안녕하세요 반갑습니다. 소영님 😄 
첫번째 PR 을 작성해주시느라 고생하셨습니다.

조금 더 개샌해보면 좋을 점들이 있어서 피드백을 남겨두었습니다.
코멘트 중에 이해가 잘 안되거나 미션진행하면서 어려운 점이 있으시면 언제든지 DM 주세요 😄 

먼저 계산기의 필수 요구사항 위주로 코드를 작성하고, 이후에 추가 요구사항을 함께 반영해보는 방향으로 해보시면 좋을것 같습니다.

> 필수 요구사항
입력을 받았을 경우 사칙연산(+, -, *, /)이 가능해야 한다.
피연산자(숫자)의 범위는 Integer로 한정한다.


미션 가이드에 있는 것 처럼 개발을 시작하기 이전에 ReadMe 를 먼저 작성하는 것이 좋은 코드를 만들 수 있다고 생각합니다. 

> 미션가이드
ReadMe에 각 객체에 대한 간단한 다이어그램(설명)을 작성한다.
ReadMe에 각 요구사항에 대한 체크 리스트를 작성한다.
커밋은 최소한의 단위로 진행한다.
객체지향 생활 체조를 지켜서 개발한다.


소영님이 생각하신 계산기 프로그램에 등장하는 객체들은 어떠한 것이 있는지, 객체들 간의 관계는 어떻게 이루어 지는 지를 생각하셔서 글, 그림을 이용하여 다이어그램을 작성해주시면 좋겠습니다.

객체지향의 언어를 사용하고 있으니 객체들을 더 적극적으로 활용하는 방향으로 같이 만들어 가보면 좋을것 같습니다. 

Git commit 은 하나의 작업 단위가 됩니다. 이는 작성하실 ReadMe 의 요구사항에 대한 체크리스트로 먼저 작성하시면서 관리 하게 되면 Commit이 크지 않고 작게 나뉠수 있으며 작게 나뉜 Commit 은 어떤 작업들을 했는지 쉽게 파악이 되기도 합니다.

아래는 체크리트에 대한 예시 입니다.
```
- [x] 계산식(문자열) 입력 받기 기능 추가
- [ ] 사칙 연산을 담당한는 Operator 라는 네이밍을 가진 Class 구현
- [ ] 문자열을 계산식에 맞는 타입으로 변환
```

한번의 커밋마다 ReadMe 의 체크 박스도 변경(추가) 하여 같이 반영이 되면 좋겠습니다.

2022-12-08 02:40 UTC, Jo-GyuHyeon commented on src/main/java/CalculatorMain.java
> +            if(cal.indexOf("*") ==-1 && cal.indexOf("/") ==-1 ) break;
멈추는 조건(유효성 검사)을 상단에 작성해주신것은 좋은것 같습니다.

하지만 종료되는 조건이 *,/ 로 되는것은 일반적으로 파악하기 힘들 수 있을것 같습니다.
우선 추가요구사항을 제외하고 필수 요구사항만 생각 해보았을때, 계산식들이 존재하고, 순차적으로 계산을 마치면 계산기는 결과를 출력한다라는 로직을 생각해보시면 좋을것 같습니다.

이때 자료구조나, 클래스, 스트림 등을 활용할 수 있을것 같습니다.

2022-12-08 02:40 UTC, Jo-GyuHyeon commented on src/main/java/CalculatorMain.java
> +            if(cal.indexOf("*") ==-1 && cal.indexOf("/") ==-1 ) break;
`==-1` 인 경우에는 `== -1` 처럼 띄워쓰기를 해주시는게 가독성에 좋습니다.

2022-12-08 02:40 UTC, Jo-GyuHyeon commented on src/main/java/CalculatorMain.java
> +                cal = cal.replace(str, String.valueOf(reuslt));
문자열을 변경하기 보다 계산결과를 별도의 변수로 기록을 하면 어떨까요?

2022-12-08 02:40 UTC, Jo-GyuHyeon commented on src/main/java/CalculatorMain.java
> +                String str = cal.substring(before +1, idx) + "*" + cal.substring(idx+1, after);//연산식
문자열을 다루기 보다 피연산자와 연산자에 맞게끔 타입을 변환한 후 순차적으로 계산을 하면 어떨까요?
연산자는 현재 (+,-,*,/) 만 다루고 있습니다. Operator 라는 네이밍을 가진 Enum class 를 만들어 보는 것도 좋을것 같습니다.
피연산자는 현재 정수형이니 문자열을 정수로 변환을 미리 해두시는건 어떨까요?

2022-12-14 16:50 UTC, merged

2022-12-14 16:53 UTC, s2s22 reviewed
요즘 컬렉션 프레임워크와 스트림에 대해서 공부하고있는데 스택이 수식계산에 사용된다하여 후위 수식계산 원리를 공부하고 코딩에 해보았습니다... 수정할 부분이나 객체지향적으로 수정할 부분 확인부탁드립니다