[1기][고범준] 문자열 계산기 과제
programmers-lecture/java-calculator pull request #2
Opened 2022-09-18 04:04 UTC by K-jun98

안녕하세요. 마르코&알 님!

우선 미션을 진행하면서 궁금했던 점이나 하고 싶었지만 남겨둔 점에 대해 먼저 얘기하겠습니다

계산식을 입력받고 정규식을 이용해서 유효성 검증을 하고 싶었지만 생각처럼 되지 않아서 제거하였습니다.

Operator 클래스를 enum을 이용하여 코드를 더 객체지향적으로 바꿀 수 있다고 생각했지만,, 구현하진 못했습니다.

객체지향적으로 코드를 짜고싶었지만 그러지 못한거같아서 책임분리나 객체지향쪽으로도 개선 방향을 제시해주시면 좋을거 같습니다!

우선 제가 봐도 코드 자체가 너무 지저분하기 때문에 리팩토링 할게 넘쳐 보이는데.. 리뷰를 받고 리팩토링을 하는 게 낫겠다고 생각하여 좀 이르게 PR 올립니다! 리뷰 주시면 반영하여 리팩토링해보도록 하겠습니다.
감사합니다👍

2022-09-18 05:03 UTC, ksy90101 requested changes
안녕하세요 범준님 :)
빠르게 구현해주셨네요.
간단한 피드백을 남겼으니, 수정해주시면 감사하겠습니다.
언제든 질문은 프로그래머스 LMS(클래스룸)또는 해당 스레드에 남겨주시면 답변 드릴게요~
고생 많으셨습니다!

2022-09-18 05:03 UTC, ksy90101 commented on src/main/java/calculator/domain/Calculator.java
> +    private List<String> formula;
해당 필드도 불변으로 할수 있을듯 합니다 :)

2022-09-18 05:03 UTC, ksy90101 commented on src/main/java/calculator/domain/Calculator.java
> +            if (formula.get(i).equals("*") || formula.get(i).equals("/")) {
`*`, `/`은 모두 매직넘버네요 :)
의미있는 단어로 작성해보면 어떨까요?

2022-09-18 05:03 UTC, ksy90101 commented on src/main/java/calculator/domain/Calculator.java
> +                    process.intCalculator(formula.get(i - 1), formula.get(i + 1), formula.get(i)));
```suggestion
                replace(i, process.intCalculator(formula.get(i - 1), formula.get(i + 1), formula.get(i)));
```

이런식으로 작성하시는것이 더 가독성이 좋아보입니다 :)

2022-09-18 05:03 UTC, ksy90101 commented on src/main/java/calculator/domain/Operator.java
> +        }
enum과 함수형 인터페이스를 이용해 전략패턴으로 구현해보면 어떨까요?

https://rutgo-letsgo.tistory.com/167

해당 내용을 참고해보세요!

2022-09-18 05:03 UTC, ksy90101 commented on src/main/java/calculator/domain/Operator.java
> +
```suggestion
public class Operator {

```

2022-09-18 05:03 UTC, ksy90101 commented on src/main/java/calculator/domain/Operator.java
> +    public String intCalculator(String startValue, String endValue, String operator) {
value라는 단어보단, operand라는 피연산자라는 단어가 더 좋아보여요!

2022-09-18 05:03 UTC, ksy90101 commented on src/main/java/calculator/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
여기도 불편을 유지해주세요.

아울러 View는 변경될 여지가 많을듯 합니다. 차후에 콘솔형태가 아닌 다른 형태로 되었을때 교체하기 편하도록 Interface로 해두면 어떨까요?

2022-09-18 05:05 UTC, K-jun98 commented on src/main/java/calculator/controller/StringCalculator.java
> +        Calculator ccc = new Calculator(InputView.inputFormula());
앗.. 나중에 수정해야지 해놓고 그대로 커밋해버렸네요 ㅎㅎ 수정하겠습니다 ㅎ

2022-09-18 06:25 UTC, K-jun98 commented on src/main/java/calculator/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
인터페이스를 추가하여 구현 하였는데 이부분에서 정확하게 인터페이스에 의존하게 적용한게 맞는지 의문이 있습니다,,

2022-09-18 08:52 UTC, SeokRae reviewed
안녕하세요. 범준님
고생하셨습니다. 마르코께서 피드백하신 부분에 대해서도 놀랍게도 빠르게 적용이 되었군요.!
궁금한 내용과 고민해볼 내용이 있어, 몇 가지 피드백 남깁니다.

![문자열계산기_고범준](https://user-images.githubusercontent.com/17922700/190893544-e20dd06d-fa6f-41f6-85ed-e47bc2105f33.png)

1. Application
	1. 클래스 생성할 때, 어떠한 목적으로 생성되는지?
	2. ①과 ②의 차이점
2. StringCalculator의 역할을 어떻게 정의하셨는지?
	1. run이라는 메서드의 로컬 변수로 InputView, Calculator가 생성
	2. OutputView의 경우에는 객체를 생성하는 것이 아니라 정적 팩토리 메서드를 통해 결과 값을 출력하게끔 되어 있는데 이유가 있는지?
3. InputView 인터페이스
	1. 인터페이스에서 만들어지는 추상 메서드는 public static이 기본으로 붙기 때문에 public 접근제한자를 붙이지 않아도 될 것 같습니다.
4. InputView 구현체
	1. static 으로 만들어진 객체와 static final로 만들어진 필드는 어떠한 차이점이 있을지? 
	   (현재 프로그램에서 Scanner는 어떠한 역할을 하고 있어 어떠한 설정이 필요한지)
5. OutputView
	1. 정적 팩토리 메서드를 하나만 제공하고 있고, 추후에도 정적 팩토리 메서드만을 제공할 예정이라면 private 생성자를 통해 객체를 불필요하게 생성하지 못하도록 제한 하는 것을 권장합니다.
6. Calculator
	1. Integer.valueOf와 Integer.parseInt는 Integer와 int라는 리턴타입이 조금 다른데, 현재 상황에서는 어떠한 메서드를 사용해야 할 지 고민해보는 것도 좋을 것 같습니다.
	2. 우선순위에 대한 알고리즘에 대한 내용은 크게 커멘트 하지 않겠습니다. !
	3. 열거타입에 존재하지 않는 연산자가 중간에 들어오는 경우 어떻게 되나요?!
7. Operator
	1. DIVIDE(Calculator.DIVIDE_OPERATOR, (startOperand, endOperand) -> startOperand / endOperand);
		1. java.lang.ArithmeticException: / by zero -> 예외 처리 필요
	2. 열거 타입은 일정 개수의 상수 값을 정의한 다음, 그 외의 값은 허용하지 않는 타입이다.
		1. enum의 컨셉 상 내부에 선언되는 필드의 경우 private final을 권장합니다.
		2. enum에 없는 값의 경우, 기본값을 설정하여 선언되지 않은 값에 대한 요청이 들어오면 기본값을 반환한다던가 정의되지 않은 값이라는 예외를 발생해야 합니다.
	3. 이건 과제 내용과는 상관 없지만, String.valueOf로 결과 값을 감싸는경우 결과 값이 없으면 null이라는 문자열을 반환하는데 혹시 알고 계신가요?
	4. return Arrays.stream(values()).filter(i -> i.operator.equals(operator)).findFirst().get();
		1. 위 코드를 사용하게 되는 경우에 operator의 값이 없는 경우 enum에 정의된 상수가 없어 java.util.NoSuchElementException: No value present라는 예외가 발생할 것 같습니다.
		2. 나중에 Operator라는 열거 타입을 확장해서 개발이 필요하게되는 경우, 다른 클래스에서 이를 활용해 개발하게 되는 경우에 이 오류를 확인하게 될 것 같습니다.

이미 코드 구성이 잘 되어 있어서 내부적으로 처리되는 우선순위 알고리즘, 코드 라인 수준의 예외처리가 아닌 객체로 처리하는 부분에 대해서 앞으로 같이 학습하면 더 좋을 것 같습니다.!

2022-09-18 08:52 UTC, SeokRae commented on src/main/java/calculator/domain/Calculator.java
> +                replace(i, Operator.calculate(MULTIPLY_OPERATOR, Integer.valueOf(formula.get(i - 1)), Integer.valueOf(formula.get(i + 1))));
```suggestion
                replace(i, Operator.calculate(MULTIPLY_OPERATOR, Integer.parseInt(formula.get(i - 1)), Integer.parseInt(formula.get(i + 1))));
```

2022-09-18 08:52 UTC, SeokRae commented on src/main/java/calculator/domain/Operator.java
> +    DIVIDE(Calculator.DIVIDE_OPERATOR, (startOperand, endOperand) -> startOperand / endOperand);
```suggestion
    DIVIDE(Calculator.DIVIDE_OPERATOR, (startOperand, endOperand) -> {
		if(endOperand == 0) {
			throw new IllegalArgumentException("0으로 나눌 수 없습니다.");
		}
		return startOperand / endOperand;
    });
```

2022-09-18 08:52 UTC, SeokRae commented on src/main/java/calculator/domain/Operator.java
> +    private static Operator getOperator(String operator) {
```suggestion
    private static Operator getOperator(String operator) {
        return Arrays.stream(values())
	        .filter(i -> i.operator.equals(operator))
	        .findFirst()
	        .orElseThrow(() -> new UndefinedOperationException("정의되지 않은 연산자 입니다." + operator));
    }
```

2022-09-18 08:52 UTC, SeokRae commented on src/main/java/calculator/view/InputView.java
> +    public String[] inputFormula();
```suggestion
   String[] inputFormula();
```

2022-09-18 08:52 UTC, SeokRae commented on src/main/java/calculator/view/OutputView.java
> +
```suggestion
    private OutputView() {}
```

2022-09-18 08:52 UTC, SeokRae commented on src/main/java/calculator/view/InputViewImpl.java
> +public class InputViewImpl implements InputView{
```suggestion
public class InputViewImpl implements InputView {
```

2022-09-18 08:52 UTC, SeokRae commented on src/main/java/calculator/view/OutputView.java
> +public class OutputView{
```suggestion
public class OutputView {
```

2022-09-18 10:24 UTC, K-jun98 commented
> 1. Application
>    
>    1. 클래스 생성할 때, 어떠한 목적으로 생성되는지?
         Application클래스는 따로 생성할지 말지 고민했으나 contoller에 main메서드를 두는것보다 따로 Application 클래스를 만드는게 좋겠다고 생각했습니다.
>    2. ①과 ②의 차이점

> 2. StringCalculator의 역할을 어떻게 정의하셨는지?
>    
>    1. run이라는 메서드의 로컬 변수로 InputView, Calculator가 생성
     지금보니 run이라는 메서드로 모두 정의하기보단 StringCalaulator에서도 메서드를 나눠서 정의하고 지금 Application클래스에서 이용하는게 좋을거 같다는 생각이 드는데 어떻게 생각하시는지 궁금합니다.
>    2. OutputView의 경우에는 객체를 생성하는 것이 아니라 정적 팩토리 메서드를 통해 결과 값을 출력하게끔 되어 있는데 이유가 있는지?
       OutputView클래스 멤버변수를 사용하는일이 없기때문에 정적으로 선언해도 좋다고 생각했습니다.

> 3. InputView 인터페이스
>    
>    1. 인터페이스에서 만들어지는 추상 메서드는 public static이 기본으로 붙기 때문에 public 접근제한자를 붙이지 않아도 될 것 같습니다.
          수정하도록 하겠습니다!

> 4. InputView 구현체
>    
>    1. static 으로 만들어진 객체와 static final로 만들어진 필드는 어떠한 차이점이 있을지?
>       (현재 프로그램에서 Scanner는 어떠한 역할을 하고 있어 어떠한 설정이 필요한지)
원래 코드에서는 InputView클래스 역시 정적 메서드 였기때문에 객체또한 정적으로 해주었는데 지금은 static을 제거해도 될거같다고 생각합니다.

> 5. OutputView
>    
>    1. 정적 팩토리 메서드를 하나만 제공하고 있고, 추후에도 정적 팩토리 메서드만을 제공할 예정이라면 private 생성자를 통해 객체를 불필요하게 생성하지 못하도록 제한 하는 것을 권장합니다.
          수정하도록 하겠습니다!

> 6. Calculator
>    
>    1. Integer.valueOf와 Integer.parseInt는 Integer와 int라는 리턴타입이 조금 다른데, 현재 상황에서는 어떠한 메서드를 사용해야 할 지 고민해보는 것도 좋을 것 같습니다.
>    2. 우선순위에 대한 알고리즘에 대한 내용은 크게 커멘트 하지 않겠습니다. !
>    3. 열거타입에 존재하지 않는 연산자가 중간에 들어오는 경우 어떻게 되나요?!
  열거타입에 존재하는 않는 연산자가 입력되는 경우엔 정규식을 이용하여 유효성검증을 진행하고 싶었지만.. 구현하지 못하엿습니다ㅠㅠ

> 7. Operator
>    
>    1. DIVIDE(Calculator.DIVIDE_OPERATOR, (startOperand, endOperand) -> startOperand / endOperand);
>       
>       1. java.lang.ArithmeticException: / by zero -> 예외 처리 필요
>    2. 열거 타입은 일정 개수의 상수 값을 정의한 다음, 그 외의 값은 허용하지 않는 타입이다.
>       
>       1. enum의 컨셉 상 내부에 선언되는 필드의 경우 private final을 권장합니다.
public static final String PLUS_OPERATOR = "+"; 이부분을 private final 로 수정하여 사용하고 다른 클래스에서 getter를 이용해 사용하는걸 말씀하시는걸까요? 정확히 이해를 못하였습니다 ㅠ
>       2. enum에 없는 값의 경우, 기본값을 설정하여 선언되지 않은 값에 대한 요청이 들어오면 기본값을 반환한다던가 정의되지 않은 값이라는 예외를 발생해야 합니다.
>    3. 이건 과제 내용과는 상관 없지만, String.valueOf로 결과 값을 감싸는경우 결과 값이 없으면 null이라는 문자열을 반환하는데 혹시 알고 계신가요?
>    4. return Arrays.stream(values()).filter(i -> i.operator.equals(operator)).findFirst().get();
>       
>       1. 위 코드를 사용하게 되는 경우에 operator의 값이 없는 경우 enum에 정의된 상수가 없어 java.util.NoSuchElementException: No value present라는 예외가 발생할 것 같습니다.
       역시 유효성검증을 추가하면 좋을거같습니다,,ㅠ
>       2. 나중에 Operator라는 열거 타입을 확장해서 개발이 필요하게되는 경우, 다른 클래스에서 이를 활용해 개발하게 되는 경우에 이 오류를 확인하게 될 것 같습니다.
> 
> 이미 코드 구성이 잘 되어 있어서 내부적으로 처리되는 우선순위 알고리즘, 코드 라인 수준의 예외처리가 아닌 객체로 처리하는 부분에 대해서 앞으로 같이 학습하면 더 좋을 것 같습니다.!

알님 피드백 감사합니다!
제가 작성한 코드임에도 다시 한번 생각해 볼 수 있었던 피드백인 거 같습니다!
우선 알 님이 남겨주신 피드백과 질문의 내용을 제 생각대로 답을 해보았는데. 아직 정확한 근거를 갖고 결정한 부분이 많이 없는 거 같아서 추가로 보면 좋을 자료나 주제를 주신다면 감사하겠습니다!

2022-09-25 09:21 UTC, K-jun98 commented on src/main/java/calculator/domain/Operator.java
> +    DIVIDE(Calculator.DIVIDE_OPERATOR, (startOperand, endOperand) -> startOperand / endOperand);
이 경우에 "0으로 나눌 수 없습니다." 예외 메시지를 상수 처리하게되면 상수 클래스가 만들어지게 되던데 이런 과하다고 생각되어 직접 명시하였습니다. 알님의 의견은 어떠신지 궁금합니다!

2022-09-25 09:31 UTC, K-jun98 commented on src/main/java/calculator/domain/Operator.java
> +    private static Operator getOperator(String operator) {
커스텀 예외를 추가로 공부해 보겠습니다!

2022-09-25 12:24 UTC, merged