[3기][김찬희] 문자열 계산기 구현
programmers-lecture/java-calculator pull request #20
Opened 2022-12-08 08:16 UTC by Chani17

1주차에 배운 stream을 사용해서 구현하고 싶었는데.. 아직은 응용하는데 어려움을 느껴 일단 main에 다 때려 박아버렸습니당.. 
어디에 내놓기 너무 부끄러운 코드네요..😅
그냥 닥치는대로 짜다 보니 객체지향적이지도 못한것 같기도 하고.. 더 많은 시간을 투자해서 생각을 해봐야겠습니다....
앞으로 자바 학습과 리팩토링의 목적으로 점차 클린한 코드를 작성해 볼 수 있도록 개선해보겠습니다🔥

시험이 오늘에서야 끝나서 늦었습니다,, 죄송합니다..!!

2022-12-08 08:52 UTC, Jo-GyuHyeon requested changes
안녕하세요 찬희님 😄  반갑습니다.
첫번째 미션을 하시느라 고생많으셨습니다.

도움이 될만한 피드백을 남겨두었으니, 참고해주시면 좋을것 같아요.

코드 피드백 이외에 commit 단위가 크다고 생각이 됩니다. ReadMe 에 작성해주셨던 체크리스트 처럼, 하나의 구현이 끝날때마다 체크박스를 체크 한 후 체크단위 마다 Commit 을 나뉘게 되면 작은단위로 Commit 이 관리 될 것이고 작업단위를 쉽게 파악하기 용이합니다.

다음 PR 에서는 해당 부분을 적용해보시는것도 좋을것 같습니다.

2022-12-08 08:52 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +    }
연산자의 역할을 담당하는 Operator 라는 클래스로 분리를 해보면 어떨까요? 이때 클래스는 Enum 을 활용 할 수 있을것 같습니다. :) 

연산자에 대한 종류, 행동에 대한 책임을 해당 객체로 분리 할 수 있을것이라 생각합니다.

2022-12-08 08:52 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +            }
else 조건은 *, / 이외에 다른 특수문자가 존재하거나, 잘못된 계산식일 경우에도 해당 else 구문으로 동작하게 될것 같습니다. 
잘못된 입력에 대한 검증도 미리 할 수 있다면 더 좋을것 같습니다.

2022-12-08 08:52 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +        Stack<String> operator = new Stack<>();         // 사칙연산 부호 저장 배열
위의 numbers 처럼 operator 도 복수형의 네이밍은 어떨까요?

2022-12-08 08:52 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +    }
우선순위 먼저 계산후 나머지 계산하는 로직으로 잘 작성해주셨군요.
다만 numbers, operators 가 아닌  number 와 operator 라는 필드를 가진 수식이라는 클래스를 별로 생성하는 것은 어떨까요? 
그렇게 된다면 잘못된 수식일 경우에도 해당 클래스에서 책임지고 예외를 발생 시킬 수 있을뿐더러, 인덱스를 조작하는 방식이 아닌 객체를 이용하는 방식으로 가독성도 더 좋아 질 것이라 기대를 합니다. :)


추가:
우선순위 계산과, 후순위 계산을 별도의 메서드로 분리를 하게 되면 더 쉽게 코드가 읽히고 간력해질것이라 생각이 됩니다.

2022-12-10 06:39 UTC, Chani17 commented on src/main/java/Calculator.java
> +    }
"다만 numbers, operators 가 아닌 number 와 operator 라는 필드를 가진 수식이라는 클래스를 별로 생성하는 것은 어떨까요?" 이 부분이 잘 이해가 되지 않습니다ㅜㅜ 
numbers와 operators 스택에서 값을 받아오고 나서 처리하는 부분만 클래스를 생성해서 구현해보라는 말씀이실까요...??

2022-12-10 11:04 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +    }
찬희님 다시 물어봐주셔서 좋습니다. 👍 

피연산자와 연산자 필드를 가진 수식 클래스로 만들어 보라고 한 피드백은 현재 Calculator 에서 객체 끼리 협럭이 아닌 Calculator 내의 numbers, operators 각 필드를 조작하는 방식으로 로직이 작성되어 있어서 별도의 수식역할을 담당하는 클래스를 만들어 보면 좋겠다는 의견이였습니다.

class Person(){ String name; int age}  처럼 수식의 정보들을 담고 있는 class 수식(){Operator operator; int Operand;} 과 같은 형태 입니다.

위의 피드백 처럼 Calculator 에서 인덱스를 이용한 (데이터를 직접 조작) 하기 보다 객체끼리 협럭으로 이루어지는것이 객체를 더 잘 활용하고 책임분리 하기 용이 하다고 생각합니다.


계산기 로직의 흐름을 살펴 보면  `문자열 입력 -> 수식 변환 -> 수식 기반으로 계산 -> 총 합` 의 흐름으로 알고 있습니다.
Calculator의 행동과 책임은 수식을 계산만 하면 된다고 생각하고 있습니다.

현재 코드 기준으로 보았을때 Stack<String> operators 보다는 Stack<Operator> operators 를 활용하면 아래의 코드에서 if 문으로 분기 처리를 하지 않으실 수 있습니다.

```
for(int i=0; i<operators.size(); i++) {
            if (operators.get(i).equals("+")) {
                result = Operator.PLUS.apply(numbers.pop(), numbers.pop());
                numbers.push(result);
            } else {
                result = Operator.SUBTRACT.apply(numbers.pop(), numbers.pop());
                numbers.push(result);
            }
}
```

코드를 보시면 아시겠지만 수식은 연산자와 피연산자가 필요합니다. (number, operator) 필드를 가진 수식 객체로 변환하여 계산 로직에 이용한다면 수식들에 대한 연속적인 계산만 하면 될것 이라 생각합니다.

(현재는 우선순위 계산을 제외하시고 순차적인 계산만 고려를 먼저하시면 더 편하실것 같습니다.)

ex) 1 + 2 - 1 * 3 이라는 문자열이 있다면 수식 객체는  [ (1 , +) , (2, -), (1, *), (3, +) ] 으로 표현할 수 있을것 같습니다. 이때 마지막 3 에 + 연산자는 짝을 맞추기 위해 추가 해줄 수도 있으며 뒤에 다른 수식이 있지 않으니 + 0 을 해주는 효과랑 동일하다고 생각합니다.

2022-12-10 11:07 UTC, Jo-GyuHyeon requested changes

2022-12-10 11:07 UTC, Jo-GyuHyeon commented on src/main/java/Operator.java
> +    }
생성자를 만들었지만 Calculator에서 실제 사용하고 있지 않은것 같습니다.
Operator 를 이용하면 문자열 비교하지 않고, 객체를 이용한 로직들을 작성할 수 있을 것 같습니다. 😄

2022-12-30 04:18 UTC, merged