[3기][김수민] 문자열 계산기 과제
programmers-lecture/java-calculator pull request #21
Opened 2022-12-08 09:45 UTC by kssumin

2022-12-08 12:02 UTC, Jo-GyuHyeon commented on src/main/java/utils/StringParser.java
> +    }
pase 라는 의미에 맞게끔 String 타입이 아닌 Operator 타입 혹은 int 타입으로 변환을 하는 것이 추후에 객체들 간의 협력한다는 의미로 보여줄수 있다고 생각해요 :)

2022-12-08 12:09 UTC, Jo-GyuHyeon commented on src/main/java/utils/StringParser.java
> +    }
질문에 대한 저의 생각은, 아래의 메서드는 해당 parInput 기반으로 동작할 수 있다고 생각하기도 하며, 다른 객체들이 해당 메서드를 사용하느냐에 따라 가시성을 변경할것 같습니다.

지금 메서드 네이밍을 보았을때 parse 의 기능보다는 split 의 기능이니 main 혹은 controller 에서 해당 기능을 사용하기 보다는 아래의 parse 메서드의 공통 기능을 private 하게 추출하는 형태로 해석 하고 있습니다.

다만 걱정하실 부분이 불필요하게 parseInput(Split) 을 한번더 하게 되지 않을까? 가 될것 같은데, 이는 parseOperand, parseOperator 를 분리하지 않고 하나의 paserExpression 메서드로 만들어 보는 것은 어떨까요?

2022-12-08 12:09 UTC, Jo-GyuHyeon commented on src/main/java/Operator.java
> +public enum Operator {
Enum 클래스를 잘 활용하신것 같습니다. :)

2022-12-08 12:10 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +                .filter(x -> x.getOperation().equals(operation))
x 보다는 조금더 의미 있는 네이밍을 부여하면 어떨끼요?

2022-12-08 12:12 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +    }
Stream 을 잘 활용하셨습니다.

Operator 의 정적 펙토리 메서드를 사용하는 방법을 어떨까요? 존재 하지 않다면 예외도 발생하여 Operator 객체에 책임을 맡겨보는 방향도 고려해보면 좋을것 같습니다.

2022-12-08 12:14 UTC, Jo-GyuHyeon commented on src/main/java/Application.java
> +        OutputView.result(result.getResult(result.resultListLastNumber()));
메인 내에서도 어떠한 행위들이 일어나는지 private 메서드로 분리를 한다면 main 은 메서드들만 보게 되어 가독성과 책임을 분리 할수 있을것이라 생각이 됩니다.

2022-12-08 12:15 UTC, Jo-GyuHyeon requested changes
안녕하세요 수민님 :) 반갑습니다.
대체적으로 잘 구현을 해주셨습니다. 
아래에 도움이 될만한 피드백을 남겨두었는데 한번 참고 해주시면 좋을것 같습니다. :)

2022-12-11 02:46 UTC, kssumin commented on src/main/java/utils/StringParser.java
> +    }
parse가 해당 타입으로 변경해준다 라는 의미를 가지고 있기에 Operator, Int 으로 리턴타입으로 변경하는게 좋다. 그럼 해당 메시지가 가지고 있는 책임을 더 명확히 충족시켜준다. 따라서  객체들간의 도움을 요청할 때  String 보다는 Integer로 변환을 하는게 메시지에 맞게 책임을 더 잘 수행하고 있는거여서 객체들간의 협력을 보여준다는 것인가요..?

2022-12-11 02:46 UTC, kssumin commented on src/main/java/Calculator.java
> +                .filter(x -> x.getOperation().equals(operation))
넵! 연산자라는 의미를 더 가져갈 수 있도록 네이밍을 변경하겠습니다!

2022-12-11 02:59 UTC, Jo-GyuHyeon commented on src/main/java/utils/StringParser.java
> +    }
맞습니다. 현재 시점의 Application 의 코드를 보았을때 paser 동작 후 Calculator 의 생성자에 필요한 인자를 Application 로직에서 타입 변환을 하고 있을 것을 볼 수 있습니다.

```
for (int index = 0; index < operandList.size(); index++) {
  Calculator calculator = new Calculator(result.getResult(index), operandList.get(index), operatorList.get(index));
  result.addResultList(calculator.calculateNumber());
}
```

Calcualtor 와 Parser 객체간의 협력을 할 수 있도록 수식이라는 객체를 만들어서 메시지를 주고 받으면 어떨까요?

2022-12-14 05:00 UTC, kssumin commented on src/main/java/Calculator.java
> +    }
enum을 단순히 상수의 집합이라고 생각해서 enum에 정적 팩토리 메세더를 적용하는것에 어려움을 겪었습니다.

1번
```
private static final int WEST = 0;
private static final int EAST = 1;
```

2번
```
private static final Direction WEST = Direction();
private static final Direction EAST = Direction();
```

3번
```
enum Direction{
 WEST,EAST
}
```

enum이 위 과정을 표현한 것입니다.
따라서, 정적 팩토리 메서드 패턴은 불필요한 객체 생성을 반복하지 않고 이미 생성한 객체를 재활용하는 것이므로 enum이 2번을 변형한 것이라고 생각한다면 정적 팩토리 메서드을 사용할 수 있을 것같습니다.

또한, 말씀해주신 것처럼 Calcalator가 입력받은 operation이 있는지 없는지 확인하는 것보단  Operator객체에게 메시지를 주고 본인이 가지고 있는 상태값을 객체 자신이 확인하는 게 더 좋을 것 같습니다. 

리뷰해주신 덕분에 enum에 대해서 공부할 수 있었습니다. 감사합니다

2022-12-14 07:00 UTC, kssumin commented on src/main/java/utils/StringParser.java
> +    }
Expression 객체가 하는 역할을 잘 모르겠습니다.
현재 클래스에서 spit만하고, Expression 객체에서 수식이 올바른지 확인하는 절차를 거치면 되는 걸까요?

2022-12-14 07:00 UTC, kssumin commented on src/main/java/utils/StringParser.java
> +    }
마찬가지로, 그럼 Expression 객체에서 타입변환을 하고, Calculator 생성자에 Expression만을 이용해서 Application에서 내부 로직이 안 보이게 하면 되는걸까요?

2022-12-14 07:00 UTC, kssumin commented on src/main/java/utils/StringParser.java
> +    }
또, main, controller의 역할에 대해 잘 모르겠습니다.

Controller는 사용자가 요청한 웹 페이지를 서비스 하기 위해 모델을 호출한다.
이 관점에서 봤을 때 controller는 내부 비즈니스를 보여주지 말고, 요청을 받고 응답을 하는 계층으로만 봐서 split또한 main에서 사용을 자제하라는 말씀인가요?

2022-12-14 07:09 UTC, Jo-GyuHyeon commented on src/main/java/utils/StringParser.java
> +    }
넵 맞습니다. 최대한 로직은 객체 안에서 작성되고 Application 에서는 객체들을 이용하는 형태로만 표현 해볼수 있을 것 같습니다.

2022-12-14 07:16 UTC, Jo-GyuHyeon commented on src/main/java/utils/StringParser.java
> +    }
main, controller, Application 전부 로직을 직접 구현해야 하는 곳이 아니라 로직이 구현된 객체들을 이용하는 영역(책임)이라 생각이 됩니다.
웹 페이지에서의 controller 또한 로직이 구현이 되어 있는 service 객체에게 로직을 실행 시키는 것과 유사하게 바라볼수 있을 것 같습니다.

Expression 객체의 역할을 메시지 형식을 담당하는 역할이 있다고 생각합니다. (데이터를 담기 위한 용도)
다른 예시를 들면 영수증과 마찬가지로 가격, 일자, 등등 영수증에 담겨야 할 포맷(내용) 들이 존재하는 클래스 (데이터를 담기 위한 용도) 라고 생각해보시면 어떨까요? 물론 영수증도 올바른 형식으로 작성되어 있는지는 영수증이 책임지고 확인 할 수 있다고 봅니다.

2022-12-19 02:25 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +    }
operator에서 구현한 메서드가 있는데 Calculator 에서 한번더 감싸줄 필요가 있을까요?

2022-12-19 02:25 UTC, Jo-GyuHyeon commented on src/main/java/Application.java
> +        OutputView.result(result.getResult(result.resultListLastNumber()));
result.getResult(result.resultListLastNumber()) 를 한번에 동작시키는 메서드로 만들어 보는건 어떨까요?

2022-12-19 02:25 UTC, Jo-GyuHyeon commented on src/main/java/Calculator.java
> +            return Integer.parseInt(a);
파라미터 네이밍은 최대한 의미가 있으면 좋을것 같습니다.

2022-12-30 04:19 UTC, merged