[3기][Chemi] 자바 문자열 계산기 #1
programmers-lecture/java-calculator pull request #22
Opened 2022-12-08 11:56 UTC by HandmadeCloud

1. 사칙연산을 판단하고 연산하는 부분을  enum 활용기 블로그를 통해서 따라 구현해보았습니다.
2. MVC 패턴에 맞춰 나누고 클래스를 생성하였습니다.

but 
3.  Calculator 클래스에서 calculatorType enum 클래스의 연산 메소드를 실행하려고 했지만, 오류가 발생하고 있지만 어떻게 해결해야 할 지 방법을 찾지 못해 일단 돌아가게 만드는 것에 실패한 상황입니다..

2022-12-11 04:12 UTC, ksy90101 commented on src/main/java/controller/Calculator.java
> +            result = calculatorType.operate(result, next_num);
개행도 하나의 의미를 가지게 됩니다.
```suggestion
            int next_num = Integer.parseInt(expression[i]);

            result = calculatorType.operate(result, next_num);
```
의미없는 개행은 피해주세요 :)

2022-12-11 04:12 UTC, ksy90101 commented on src/main/java/controller/CalculatorController.java
> +        String[] expression = content.split(" ");
" "이거에 대한 의미를 나타내기 위해 상수화를 한번 해보면 어떠신가요?

2022-12-11 04:14 UTC, ksy90101 commented on src/main/java/model/CalculatorType.java
> +    DIVIDE("/", (left,right) -> left / right);
```suggestion
    // 나중에 분모 0 처리 방법 고민해보기
    DIVIDE("/", (left,right) -> {
       if(분모가 0이냐?) { 에러처리 }
       return left / right
    });
```

이런식으로 사용한다면 0도 처리 가능하겠네요 :)

2022-12-11 04:14 UTC, ksy90101 commented on src/main/java/model/CalculatorType.java
> +    private String operator;
enum의 피드는 final이여야 하는데요 그 이유를 한번 고민해보세요

2022-12-11 04:15 UTC, ksy90101 commented on src/main/java/model/CalculatorType.java
> +public enum CalculatorType {
👍

2022-12-11 04:15 UTC, ksy90101 requested changes
전체적으로 적절하게 딱 잘 구현해주셨네요 👍 
간단한 피드백을 남겼으니 한번 참고해보세요

2022-12-13 14:55 UTC, SeokRae commented
안녕하세요. 재현님!
우선순위라는 기능을 추가하는데 도움이 될 수 있을 지는 모르겠지만 몇 가지 피드백을 드리고자 합니다.

일단 구현되어 있는 내용을 확인해보니 사용자로부터 입력 받은 식을 앞에서 부터 순차적으로 연산하는 방식으로 보여집니다.
제가 알기로는 이러한 방식으로도 물론 풀어낼 수 있지만 우선순위를 위해 뒤에까지 확인하고 하는 과정들 때문에 반복문과 조건절이 많이 들어갈 것 같습니다. 

그래서 제가 권해드리고 싶은 방식은 중위 표기법을 후기 표기법으로 변경하기, 후기 표기법을 stack을 이용하여 알고리즘으로 풀어내는 방법이 있습니다. 

대게 알고리즘 사이트에서 자주 사용되는 풀이 방법인데 이를 적용해보시는 것을 추천드립니다.
- [basic-calculator-ii](https://leetcode.com/problems/basic-calculator-ii/)

[discussion](https://leetcode.com/problems/basic-calculator-ii/discussion/)이나 [solution](https://leetcode.com/problems/basic-calculator-ii/solutions/) 내용을 참고해보시면서 다양한 방법으로 접근해보시는 것을 추천드립니다.

2023-01-22 09:33 UTC, merged