[4기][김동규] 문자열 계산기 과제
programmers-lecture/java-calculator pull request #29
Opened 2023-01-20 12:55 UTC by ehdrbrb

안녕하세요!
사칙연산에 우선순위를 두지 않고 계산하여 결과를 출력하도록 구현하였습니다.
부족한 부분 많이 지적해주시면 열심히 개선하겠습니다!
감사합니다.

2023-01-22 07:35 UTC, ksy90101 commented on src/main/java/Calculation.java
> +}
기본적으로 제공해주는 함수형 인터페이스를 사용해보면 어떨까요?
두개의 인자를 받아 Return하는 `BiFunction`이 있어요 ㅎㅎ 
한번 찾아보고 함수형 인터페이스를 이용해 람다를 한번 사용해보면 어떨까요?

2023-01-22 07:35 UTC, ksy90101 commented on src/main/java/Calculator.java
> +    Expression expression;
default 접근 제어자를 사용하신 이유가 있나요?

2023-01-22 07:37 UTC, ksy90101 commented on src/main/java/Calculator.java
> +    }
if문을 쓰다 보면, 조건에 따라 메서드가 점점 커지게 됩니다.
enum을 이용해서 한번 이 부분을 전략패턴으로 풀어보면 어떨까요?
https://rutgo-letsgo.tistory.com/167
이글을 한번 참고해보시면 좋습니다 :)

2023-01-22 07:37 UTC, ksy90101 commented on src/main/java/Calculator.java
> +
```suggestion
}

```

2023-01-22 07:37 UTC, ksy90101 commented on src/main/java/Calculator.java
> +        while (true) {
while true라면, 중지는 어떻게 하나요?

2023-01-22 07:38 UTC, ksy90101 commented on src/main/java/Expression.java
> +                numbers.add(Double.valueOf(expression[i]));
2라는게 어떤걸 의미하는지 매직넘버를 상수화 시켜보면 어떨까요?
저 처럼, 동규님의 코드를 처음 보는 사람은 2라는것이 무엇인지 알기가 어렵습니다 ㅎㅎ

2023-01-22 07:40 UTC, ksy90101 commented on src/main/java/Calculator.java
> +    private double calculate (List<Double> numbers, List<String> operators) {
```suggestion
    private double calculate(List<Double> numbers, List<String> operators) {
```

2023-01-22 07:41 UTC, ksy90101 commented on src/main/java/Calculator.java
> +    public static void main(String[] args) {
실제 실행하는 Application class가 따로 있고.
Caclulator라는 객체가 있고, Calculator라는 인스턴스를 만들어서, 계산기를 만들어 보면 어떨까요?
지금 같은 구조라면 새로운 기능이 추가될때 main메서드에서 모든걸 해야 할거에요.

2023-01-22 07:43 UTC, ksy90101 requested changes
안녕하세요 :) 동규님
설연휴에도 미션 하시느라 고생 많으셨습니다 💯 
간단한 피드백을 남겼으니 한번 확인해주세요.

마지막으로, 패키지를 이용해 객체들을 분류해보세요.
저희가 컴퓨터 파일을 관리할때, 한 폴더에 모두다 있으면 헷갈리잖아요.
그런 의미로 패키지라는게 존재합니다.
패키지로 예를들어 Calculation들을 구분해두고, Application class를 분리해두면, 차후에 훨씬 파일찾기가 쉬워질거에요..

질문이 있다면 언제든 편히 슬랙이나 LMS를 통해 맨션주세요~

cf) 코드리뷰 반영을 모두 완료했다면, Slack채널에 맨션주세요~

2023-01-22 09:32 UTC, SeokRae reviewed
안녕하세요. 동규님! 고생하셨습니다.

몇 가지 피드백 남겨보았습니다.

1. 자바 프로그램의 패키지를 사용하기

- 패키지의 활용 [oracle docs](https://docs.oracle.com/javase/tutorial/java/package/packages.html) 
  - 개발 된 클래스의 유형이 관련되어 있음을 쉽게 판단할 수 있다.
  - 패키지라는 네임스페이스를 생성하여 다른 패키지의 클래스명과 충돌하지 않는다.
  - 패키지 내에 클래스 간에 서로 제한 없이 엑세스 할 수 있는 default-private를 활용하여 패키지 외부의 액

2. 전략패턴의 활용

전략 패턴이라 하는 내용이 코드만으로는 쉽게 와닿지 않을 수 있습니다. 그림으로 한번 살펴보시고, 클래스들 간의 구성을 어떻게 이루어지는지, 이를 활용하는 입장인 "클라이언트" 클래스에서는 어떻게 전략 패턴을 사용하는지 확인해보는 것도 좋을 듯 합니다.

- [전략 패턴](https://refactoring.guru/ko/design-patterns/strategy)

고민해보시고, 의문이 가는 부분은 대댓글로 남겨주시면 답변 남겨보도록 하겠습니다.

3. SOLID의 SRP(Single Responsibility Principle)

자바 코드를 작성할 때 SRP가 최우선으로 이루어져야 하는데, 왜 그러한지 한번 알아보는 것도 좋을 듯 하네요.!

- [Baeldung - SRP](https://www.baeldung.com/java-single-responsibility-principle)

---

<img width="888" alt="CleanShot 2023-01-22 at 17 47 01@2x" src="https://user-images.githubusercontent.com/17922700/213907564-e2cc6c21-b67f-44a1-b0a0-99dd28d3975c.png">



화이팅 입니다.!!

2023-01-22 09:32 UTC, SeokRae commented on src/main/java/Calculation.java
> +public interface Calculation {
더하기 / 빼기 / 곱하기 / 나누기의 공통적인 속성은 두 피 연산자를 연산자라는 기준으로 "연산"한다. 라는
추상화 또는 일반화로 사용할 수 있는 인터페이스를 활용하신 것은 좋습니다. ! 

다만 이를 활용하는 쪽에서 인터페이스를 적극 사용하지 못하고 있는 것으로 보이네요.
마르코께서 커멘트 해주신 내용처럼 표준 함수형 인터페이스를 활용하실 수도 있고. 구현하신 인터페이스에 @FunctionalInterface 라는 어노테이션을 마킹하여 사용자 정의 함수형 인터페이스임을 명시하시는 방법도 좋습니다.

2023-01-22 09:32 UTC, SeokRae commented on src/main/java/Calculator.java
> +public class Calculator {
Calculator라는 클래스가 생성될 때 연산 처리를 수행하는 클래스들을 주입받아서 실행하는 것도 좋지만 

이미 정의해놓으신 Calculation Interface의 calculate() 메서드를 호출하면 알아서 연산자에 매핑되는 연산처리(Addition, Subtraction, Multiplication, Division)를 해주는 타입을 정의하여 연산처리를 해야 하는 책임을 위임하는 것은 어떨까요?

2023-01-22 09:32 UTC, SeokRae commented on src/main/java/Calculator.java
> +            num1 = getCalculation(operator).calculate(num1, num2);
식을 순회하면서 연산자에 해당하는 연산처리를 연결하여 연산처리가 이루어지도록 하셨군요.! 👍

2023-01-22 09:32 UTC, SeokRae commented on src/main/java/Expression.java
> +                numbers.add(Double.valueOf(expression[i]));
매직넘버에 대한 내용은 위키를 참고하셔도 좋습니다.
[매직넘버](https://en.wikipedia.org/wiki/Magic_number_(programming))

2023-01-22 11:43 UTC, ehdrbrb commented on src/main/java/Calculator.java
> +    Expression expression;
아... 제가 접근 제어자에 대한 고민을 하지 않고 default로 했네요.
private 접근 제어자를 사용하는게 나을 것 같습니다!
감사합니다.

2023-01-22 11:45 UTC, ehdrbrb commented on src/main/java/Calculation.java
> +}
기본적으로 제공해주는 함수형 인터페이스를 사용하여 개선하여 보겠습니다.
감사합니다.

2023-01-22 11:47 UTC, ehdrbrb commented on src/main/java/Calculator.java
> +    }
enum과 전략패턴에 대한 내용을 공부하여 수정해보도록 하겠습니다.
감사합니다.

2023-01-22 11:48 UTC, ehdrbrb commented on src/main/java/Calculator.java
> +        while (true) {
해당 부분은 미처 고려하지 못했습니다.
중지할 수 있는 조건을 넣어 해당하는 입력이 들어오면 중지하도록 해보겠습니다.
감사합니다.

2023-01-23 05:14 UTC, ehdrbrb commented on src/main/java/Expression.java
> +                numbers.add(Double.valueOf(expression[i]));
말씀해주신 부분 고려하여 개선해보도록 하겠습니다.
감사합니다

2023-01-23 05:15 UTC, ehdrbrb commented on src/main/java/Calculator.java
> +    public static void main(String[] args) {
말씀하신 구조로 개선해 보겠습니다.

2023-01-23 06:10 UTC, ehdrbrb commented on src/main/java/Calculation.java
> +public interface Calculation {
@FunctionalInterface 라는 어노테이션을 사용하여 사용자 정의 함수형 인터페이스임을 명시하게 되면

```java
    private Calculation getCalculation(String operator) {
        if (operator.equals("+")) {
            return addition;
        }
        if (operator.equals("-")) {
            return subtraction;
        }
        if (operator.equals("*")) {
            return multiplication;
        }
        if (operator.equals("/")) {
            return division;
        }
        throw new IllegalArgumentException("Illegal Argument Exception\n" + "Illegal Argument : " + operator);
    }
```
위 코드를 람다식을 활용하여 아래와 같이 변경할 수 있을 것 같습니다.
```java
private Calculation getCalculation(String operator) {
        if (operator.equals("+")) {
            return (num1, num2) -> num1 + num2;
        }
        if (operator.equals("-")) {
            return (num1, num2) -> num1 + num2;
        }
        if (operator.equals("*")) {
            return (num1, num2) -> num1 * num2;
        }
        if (operator.equals("/")) {
            return (num1, num2) -> num1 / num2;
        }
        throw new IllegalArgumentException("Illegal Argument Exception\n" + "Illegal Argument : " + operator);
    }
```
또한 Calculator 클래스의 멤버로 있던 Addition, Subtraction, Multiplication, Division이 필요가 없어질 것 같습니다.
```java
public class Calculator {
    Addition addition;
    Subtraction subtraction;
    Multiplication multiplication;
    Division division;
```


BiFunction을 활용하는 경우에도 위와 거의 유사하게 코드가 변경될 것 같습니다. 이러한 경우에 어떤 방법을 이용하는 것이 더 괜찮은 방법인지 궁금하여 질문 드립니다.
```java
//BiFunction 사용
getCalculation(operator).apply(num1, num2);
//Calculation Interface 사용
getCalculation(operator).calculate(num1, num2);
```

2023-01-23 06:17 UTC, ehdrbrb commented on src/main/java/Calculator.java
> +public class Calculator {
calculate() 메소드를 호출하면 알아서 연산자에 매핑되는 연산처리를 해주는 타입을 정의하여 연산처리를 해야 하는 책임을 위임한다는 부분을 잘 모르겠습니다. 
설명을 조금 더 부탁드려도 괜찮을까요?

2023-01-23 06:39 UTC, ehdrbrb commented on src/main/java/Expression.java
> +                numbers.add(Double.valueOf(expression[i]));
```java
final final int VALUE = 0;
public List<Double> getNumbers() {
    List<Double> numbers = new ArrayList<>();
    for(int i = 0; i < expression.length; i++) {
        if(i % 2 == VALUE) {
            numbers.add(Double.valueOf(expression[i]));
        }
    }
    return numbers;
}
```
위와 같이 변경해보았는데 제가 매직넘버를 잘 활용하지 못해 여전히 처음 보는 사람이라면 무엇인지 알기 어려울 것 같습니다. 어떻게 변경하면 좋을까요?

나름 고민하여 처음 보는 사람이 알기 쉬울 것 같은 방향으로 개선해 보았는데 어떤가요?(개선하고 보니 여기에는 매직넘버가 사용되지 않네요... 어떻게 하면 매직넘버를 사용하여 알기쉽게 바꿀 수 있을까요?ㅠㅠ)
```java
public List<Double> getNumbers() {
    List<Double> numbers = new ArrayList<>();
    for(String element : expression) {
        if(isValue(element)) {
            numbers.add(Double.valueOf(expression[i]));
        }
    }
    return numbers;
}
private static boolean isValue(String element) {
    return element.compareTo("0") >= 0 && element.compareTo("9") <= 0;
}
```

2023-01-24 19:50 UTC, SeokRae commented on src/main/java/Expression.java
> +                numbers.add(Double.valueOf(expression[i]));
매직넘버라고 부르는 개념에 대한 링크를 읽어보시면 숫자라는 값이 도메인에 따라서 다양한 의미가 부여될 수 있습니다.
그에 따라서 변수명을 짓는 것이라고 생각하시면 될 것 같습니다.
숫자 0이 금액이라는 의미에서는 0원이 될 수 있고, 현재 문자열 계산기에서는 0이라는 정수라는 범위 에서 0(ZERO)일 수 있을 것 같습니다.
그러한 명칭으로 상수로 정의해서 사용할 수 있을 것 같습니다.

2023-01-24 19:58 UTC, SeokRae commented on src/main/java/Calculation.java
> +public interface Calculation {
마르코가 제안해주신 enum을 활용해보시는 것은 어떠신가요? 연산자 개수에 대한 범위가 무한하게 커지는 것이 아니라면
열거 타입이라는 범위 안에 추가하면 되는 방식이 될 수 있을 것 같네요.

함수형 인터페이스를 정의 후, enum 안에서 사용한다거나 표준 함수형 인터페이스를 사용할 수 있을 것 같네요.

- enum 안에 연산자와 연산처리를 전략패턴으로 구현
- 연산처리에 대한 추상클래스를 만들고, 연산자에 따른 구현 클래스를 만들어 확장하는 방식

각 방법에 따라 구현체가 늘어나서 복잡도가 늘어난다거나 하는 트레이드오프가 있습니다.
구현하는 방식과 규칙은 지속적으로 구현하면서 합의점을 찾아가는 것으로 볼 수 있습니다.

2023-01-24 20:07 UTC, SeokRae commented on src/main/java/Calculator.java
> +public class Calculator {
위의 피드백에서 이야기 했듯이 
Calculator 라는 클래스에 연산자 및 피 연산자가 주어진다면, 이를 실제 처리하는 Processor라는 클래스에 calculate라는 추상 메서드만 호출하면 그 뒤에서 알아서 연산처리 구현 클래스를 찾아서 처리하게끔 하면 Calculator가 연산자 구현 클래스와의 결합도를 낮출 수 있다고 생각해서 말씀드렸습니다.

2023-01-24 23:52 UTC, ehdrbrb commented on src/main/java/Expression.java
> +                numbers.add(Double.valueOf(expression[i]));
아... 제가 매직넘버라는 것을 잘못 알고있었네요...ㅠㅠ
말씀 감사드립니다!!

2023-01-24 23:58 UTC, ehdrbrb commented on src/main/java/Calculation.java
> +public interface Calculation {
답변 감사드립니다.
덕분에 궁금증이 해소되었습니다!
감사합니다.

2023-01-25 00:00 UTC, ehdrbrb commented on src/main/java/Calculator.java
> +public class Calculator {
말씀해주신 내용 고려하여 개선해보도록 하겠습니다.
감사합니다.

2023-01-25 11:00 UTC, ksy90101 commented on src/main/java/application/Application.java
> +        System.out.println("exit을 입력하면 종료됩니다.");
차후엔 View도 한번 빼보면 좋을거 같아요.

2023-01-25 11:00 UTC, ksy90101 commented on src/main/java/application/calculator/Calculator.java
> +        setExpression(new Expression(input.split(" ")));
" " 이것또한 매직넘버이긴 해요!

2023-01-25 11:00 UTC, ksy90101 commented on src/main/java/application/calculator/Expression.java
> +    }
👍

2023-01-25 11:00 UTC, ksy90101 commented on src/main/java/application/calculator/Expression.java
> +        };
굳이 Funcation을 리턴할 필요 없고 해당 메서드에서 바로 return해도 좋을거 같아요!

2023-01-25 11:00 UTC, ksy90101 commented on src/main/java/application/calculator/Operator.java
> +public enum Operator {
👍

2023-01-25 11:01 UTC, ksy90101 commented on src/main/java/application/calculator/Operator.java
> +    }
여기서 static method를 두고 findOperator라는걸 만들어서 stream으로 순회하면서 해당 Operator enum값을 리턴하는것도 방법일듯 해요!

2023-01-25 11:02 UTC, ksy90101 requested changes
고생하셨습니다~ 간단한 피드백 하나만 더 남겼으니, 확인해주세요~

2023-01-27 07:59 UTC, ehdrbrb commented on src/main/java/application/Application.java
> +        System.out.println("exit을 입력하면 종료됩니다.");
말씀해주신 방향으로 개선하여 보도록 하겠습니다.
감사합니다.

2023-01-27 08:01 UTC, ehdrbrb commented on src/main/java/application/calculator/Calculator.java
> +        setExpression(new Expression(input.split(" ")));
매직넘버를 최소화 하도록 해보겠습니다.
감사합니다

2023-01-27 09:06 UTC, ehdrbrb commented on src/main/java/application/calculator/Operator.java
> +    }
말씀해주신 방법으로 수정해 보겠습니다.
감사합니다.

2023-01-27 09:18 UTC, ehdrbrb commented on src/main/java/application/calculator/Expression.java
> +        };
안녕하세요! 
Function을 리턴할 필요 없고 해당 메서드에서 바로 return을 해도 좋을 것 같다고 말씀해주셨는데
어떤 걸 return 해야 할지 잘 몰라서 질문드립니다.
stringToOperator() 메서드에서 바로 List<Operator>를 return 하도록 수정해보라는 말씀이신가요??

2023-01-28 11:07 UTC, ksy90101 approved these changes
테스트 코드까지 깔끔히 작성하셨네요 👍 
테스트 코드를 좀더 추가할게 있을지 조금 더 고민해보시고, 혹은 추가 미션을 하면서 리팩토링 및 테스트 코드를 작성해보면 어떨까요?

일단 1단계 미션은 머지하도록 하겠습니다~

2023-01-28 11:07 UTC, merged