Hyunseo
programmers-lecture/java-calculator pull request #3
Opened 2022-09-19 11:14 UTC by hyena0608

2022-09-19 16:04 UTC, ksy90101 requested changes
안녕하세요 현서님 :)
2주차 미션이 테스트 코드인데, 테스트 코드도 넣어주셨네요 👍 
간단한 피드백을 남겼으니, 확인해보시면 좋을듯 합니다.
전체적으로 변수명들이 a,b와 같이 알아보기 어려운 값들로 되어 잇는데요. 저희는 코드를 작성하면서 누군가에게 보여줄 글을 쓰는 작가라고 생각해봐주시면 좋을듯 합니다. 현서님 입장에선 해당 코드들을 보면 알수 있지만, 6개월뒤의 현서님이 과연 이 코드를 보고 하나의 메서드만 보고 이 메서드가 무슨 일을 하는지 알 수 있을까요? 전체적으로 클린코드의 원칙처럼 명명에 대해 신경써보시면 좋을거 같습니다.

언제든 질문이 있다면 LMS의 질문답변이나 해당 코멘트에 남겨주시면 확인하는 대로 답변 드리겠습니다.

2022-09-19 16:04 UTC, ksy90101 commented on src/test/java/calculator/CalculatorTest.java
> +        String str3 = "525 - 475";
@ParameterizedTest를 한번 보시면, 이런 부분들을 좀 더 쉽게 더 격리해서 검증할 수 있을듯 합니다 :) 
2주차때 설명 드리긴 할거에요~

2022-09-19 16:04 UTC, ksy90101 commented on src/main/java/operator/Operator.java
> +    DIVIDE("/",2, (a, b) -> a / b);
0으로 나누면 에러가 발생할텐데요. 그 부분도 예외처리를 해주셔야 할듯 합니다 :)

2022-09-19 21:33 UTC, hyena0608 commented on src/main/java/calculator/Calculator.java
> +    private void handleOperator(Stack<String> stack, String value) {
Stack을 자주 사용하다 보니 다른 생각을 안하고 사용했는데 

이렇게 하나하나 장단을 따질 수 있다는게 정말 재밌네요 !

2022-09-19 21:35 UTC, hyena0608 commented on src/test/java/calculator/CalculatorTest.java
> +    public void simplePlusTest() {
직접 이렇게 문서 링크까지 주시면서 피드백 해주셔서 너무 감사합니다 !
다른 부분도 확인해봐야겠습니다 !

2022-09-19 21:40 UTC, hyena0608 commented on src/main/java/MainApplication.java
> +import calculator.Calculator;
항상 프로젝트가 만들어진 상태에서 바로 구현해와서
폴더 계층에 대해서 생각을 해본 적이 없었는데 
이렇게 피드백 받고 기본적인 것을 좀 더 찾아봐야 겠다고 생각이 드네요 !

2022-09-19 21:48 UTC, hyena0608 commented on src/main/java/operator/Operator.java
> +    private static Map<String, Operator> MY_OPERATOR = new HashMap<>();
`MY_OPERATOR` 에서 나올 수 있는 동시성 문제는
MY_OPERATOR 내의 값이 변경된다고 했을 때 나올 수 있는 문제가 맞을까요 ?

실행 도중에 변경될 일이 없다면 동시성 문제가 생기지는 않는게 맞지만
이후 어떤 상황이 생길지 모르고 그 상황으로 동시성 문제가 발생할 수도 있으니 
`final`을 붙이라고 하신거 같다 생각했는데 제 생각이 맞을까요 ?

피드백 감사합니다 :)

2022-09-19 21:50 UTC, hyena0608 commented on src/main/java/operator/Operator.java
> +    }
오 정말이네요 ! 감사합니다 👍

2022-09-19 21:51 UTC, hyena0608 commented on src/main/java/operator/Operator.java
> +    private final BiFunction<Integer, Integer, Integer> biFunction;
위에서 피드백 해주신데로 클린코드 원칙을 좀 더 지키며 구현하겠습니다 !

2022-09-19 21:54 UTC, hyena0608 commented on src/main/java/operator/Operator.java
> +        return Optional.ofNullable(MY_OPERATOR.get(operatorType)).orElseThrow();
예외 메시지와 예외 작성 하겠습니다 👍

2022-09-19 21:54 UTC, hyena0608 commented on src/main/java/operator/Operator.java
> +    }
filter, FindFirst를 사용해서 리팩터링 해보겠습니다 ! 감사합니다 :)

2022-09-19 21:55 UTC, hyena0608 commented on src/main/java/view/Reader.java
> +    static private final BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
클린코드와 자바 컨벤션에 유의하며 구현하겠습니다 👍

2022-09-19 21:56 UTC, hyena0608 commented on src/main/java/calculator/Calculator.java
> +            int a = Integer.parseInt(stack.pop());
어떤 이름으로 둘지 몰라서 b, a로 두고 풀었는데
의미있는 단어를 작성하고자 좀 더 고민해보겠습니다 !

2022-09-19 21:59 UTC, hyena0608 commented on src/main/java/calculator/Calculator.java
> +
다른 부분이라면 신경을 쓰고 있다고 생각했지만
제가 생각하지 못하고 신경 쓰지 못한 부분들을
이렇게 콕콕 집어주셔서 감사합니다.

좀 더 신경 쓰며 구현하고 깔끔하고 좋은 코드를 작성할 수 있도록 갈고 닦겠습니다 👍

2022-09-19 22:02 UTC, hyena0608 commented on src/main/java/calculator/Calculator.java
> +        return Character.isDigit(Optional.ofNullable(value).orElseThrow().charAt(0));
정말 이 부분도 보기 힘들어서
고민하다가 차라리 한 줄이 낫다고 같다고 판단했지만
이렇게 정말 보기 좋게 만들 수 있다니 놀랍습니다.

제가 스스로 더 코드에 투자하면서 이런 보기 좋은 코드를 작성하고자 하겠습니다 :)

2022-09-19 22:04 UTC, hyena0608 commented on src/main/java/converter/FormulaConverter.java
> +    public List<String> getFormula(List<String> strings) {
String 배열을 List 에 넣어서 가져온다는 생각에 strings로 적었는데
말씀하신데로 이 코드에 있는 strings만 본다면 어떤 이유로 이 값이 있는지 파악하지 못하겠습니다.
명에 대해서 더 고민해보고 의미 있는 단어를 사용하겠습니다.

2022-09-19 22:04 UTC, hyena0608 commented on src/main/java/converter/FormulaConverter.java
> +        StringBuilder numberBuilder = new StringBuilder();
🥳

2022-09-19 22:05 UTC, hyena0608 commented on src/main/java/converter/FormulaConverter.java
> +        List<String> list = new ArrayList<>();
이 코드만 보고도 바로 파악할 수 있게 의미있는 단어를 사용하겠습니다 !

2022-09-19 22:06 UTC, hyena0608 commented on src/main/java/converter/FormulaConverter.java
> +    private void checkBracketThenPush(List<String> list, String o) {
ㅠㅠㅠ 정말 이런 의미를 알 수가 없게 작성한 부분들이 너무 많네요
그래도 이렇게 하나하나 지적해 주심에 제 코드에 문제가 있음을 인지할 수 있어서 너무 다행입니다 ㅎㅎ(?)

2022-09-19 22:07 UTC, hyena0608 commented on src/test/java/calculator/CalculatorTest.java
> +        String str3 = "525 - 475";
넵 알겠습니다 !
Junit도 정말 재밌고 간편한 부분들이 많아서 문서를 보면서 하나하나 더 깊고 자세히 테스트 해보고 싶은 욕구가 생기네요 !

2022-09-19 22:08 UTC, hyena0608 commented on src/main/java/operator/Operator.java
> +    DIVIDE("/",2, (a, b) -> a / b);
0으로 나눌 때 예외도 처리해보겠습니다 ! 감사합니다 👍

2022-09-20 12:19 UTC, ksy90101 commented on src/main/java/operator/Operator.java
> +    private static Map<String, Operator> MY_OPERATOR = new HashMap<>();
네 맞습니다. 실행 도중에 변경될 일이 없다면, 괜찮지만, 그걸 보장할순 없다고 생각이 듭니다.
아예 변경할 여지를 주지 않는것이 더 좋을듯 합니다.

2022-09-20 13:24 UTC, ksy90101 requested changes
간단한 피드백을 하나 더 남겼습니다 :)
추가 질문이 있다면 언제든 클래스룸에 작성해주세요 👍

2022-09-20 13:24 UTC, ksy90101 commented on src/main/java/stringcalculator/MainApplication.java
> +import java.util.Optional;
해당 import는 사용하지 않는듯 하네요.

2022-09-20 13:24 UTC, ksy90101 commented on src/main/java/stringcalculator/operator/Operator.java
> +    private final BiFunction<Integer, Integer, Integer> simpleCalculator;
IntBinaryOperator해당 인터페이스를 한번 알아볼까요?

2022-09-20 13:24 UTC, ksy90101 commented on src/main/java/stringcalculator/calculator/PostfixCalculator.java
> +                .orElseThrow(() -> new NullPointerException("입력하신 연산식이 잘못되어 오류가 발생하였습니다.")));
중복되는 메시지는 상수로 관리하는것이 더 좋을듯 합니다.
enum으로 예외메시지를 관리하는것도 방법일듯 하네요.

2022-09-20 13:24 UTC, ksy90101 commented on src/main/java/stringcalculator/view/Reader.java
> +    final static private BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
예약어 순서를 잘 작성해주세요.

2022-09-20 13:24 UTC, ksy90101 commented on src/main/java/stringcalculator/view/Reader.java
> +    static public List<String> read() {
여기두요 ㅠㅠ

2022-09-20 13:24 UTC, ksy90101 commented on src/main/java/stringcalculator/calculator/PostfixCalculator.java
> +        ArrayDeque<String> operandDeque = new ArrayDeque<>(formulaList.size());
Deque를 사용하니 Stack으로 구현했을때 비해 어떤 장점이 있었나요?

2022-09-20 13:24 UTC, ksy90101 commented on src/main/java/stringcalculator/calculator/PostfixCalculator.java
> +        );
이런경우에는 분리해서 작성하는것이 더 가독성이 높을수 있습니다.
예를들어, 
Character.isDigit(Optional
                .ofNullable(formula)
                .orElseThrow()
이 부분과
                .charAt(0)
이부분을 분리하는것이죠.

2022-09-20 13:24 UTC, ksy90101 commented on src/main/java/stringcalculator/operator/Operator.java
> +    public Integer calculate(Integer operandLeft, Integer operandRight) {
개행도 의미전달이 될 수 있습니다. 의미없는 개행은 하지 말아주세요.

2022-09-20 13:24 UTC, ksy90101 commented on src/main/java/stringcalculator/operator/Operator.java
> +    LEFT_BRACKET("(", 0, (a, b) -> 0),
a,b보다 더 의미는 단어를 사용하는것을 추천합니다.

2022-09-20 13:24 UTC, ksy90101 commented on src/main/java/stringcalculator/operator/Operator.java
> +    }
이 부분을 한번 없애볼까요? 충분히 없앨수 있을듯 한데요. :)

2022-09-20 21:35 UTC, hyena0608 commented on src/main/java/stringcalculator/MainApplication.java
> +        List<String> formulaList = new FormConverter().getFormula(read());
다른 곳에서 알아보기 쉽게 `-List`라고 변수명을 지어놨지만
변수명을 고정적으로 만들어 놓으니 
나중에 자료형이 변경 되기도 하니 오히려 독이 될 수 있군요 ! 😂

2022-09-20 22:01 UTC, hyena0608 commented on src/main/java/stringcalculator/calculator/PostfixCalculator.java
> +        );
하나의 메서드를 두 개의 메서드로 분리하였고
중복 메서드까지 발견하여 중복 제거까지 진행할 수 있었습니다 ! 🥳

2022-09-20 22:19 UTC, hyena0608 commented on src/main/java/stringcalculator/operator/Operator.java
> +    private final BiFunction<Integer, Integer, Integer> simpleCalculator;
기존 BiFuction 함수 인터페이스를
IntBinaryOperator으로 변경함으로서
오토 박싱, 언박싱으로 발생되는 비용을 줄일 수 있었습니다 !

2022-09-21 05:49 UTC, hyena0608 commented on src/main/java/stringcalculator/operator/Operator.java
> +    }
피드백 주셔서
필터로  enum 찾는 방식으로 다른 메서드를 구현하고
위에 Map, static 블록을 삭제할 수 있었습니다 !

2022-09-21 06:29 UTC, hyena0608 commented on src/main/java/stringcalculator/calculator/PostfixCalculator.java
> +        ArrayDeque<String> operandDeque = new ArrayDeque<>(formulaList.size());
Deque
1. 크기 할당하여 비용 최소화
   - 구현체인 ArrayDeque를 이용하여 미리 사용할 크기를 할당하여 크기를 늘려야하는 상황을 피해 비용을 줄일 수 있었습니다.

2. 단일 스레드로 필요 없는 lock을 사용하지 않는다.
    - 현재 Deque를 사용하는 PostfixCalculator에서는 동시성 문제가 없기 때문에 Stack에 기본으로 있는 lock을 사용하여 비용을 늘리는 일을 없앨 수 있었습니다.


👍

2022-09-22 00:45 UTC, ksy90101 approved these changes
안녕하세요 현서님 :)
전체적으로 피드백 적용해주시느라 고생 많으셨습니다.
현서님의 코드를 보고 저도 많은 부분들을 배울수 있었습니다. 현서님도 많은 부분을 배웠을꺼라 믿습니다.
2단계 미션(테스트 코드)이 또 준비되어 있기 때문에, 2단계 미션을 위해 1단계는 이만 머지하도록 하겠습니다.
2단계때 테스트 코드 작성 파이팅입니다!

2022-09-22 00:45 UTC, merged