[1기][정지환] 문자열 계산기 과제
programmers-lecture/java-calculator pull request #4
Opened 2022-09-19 20:39 UTC by JEONG-JIHWAN

많이 부족하지만 어떻게 리팩토링을 해야할지 전혀 모르겠어서 코멘트를 받아보려합니다 ㅜㅜ ...
Enum을 이용하는것은 다른분이 하신거에 코멘트로 링크 달아주신거 보고 해당 링크 참조했습니다.
필수 요구사항 이후 추가 요구사항을 구현할때 기존 코드를 많이 바꿔야하는 것을 봐서 전혀 객체지향적이지 못한것 같습니다....
코드는 물론이고 미션가이드도 잘 못지킨것같구 커밋도 막무가내로 한것 같은데 세세한것까지 많이 짚어주시면 감사하겠습니다!!

2022-09-20 13:47 UTC, ksy90101 requested changes
안녕하세요 지환님 :)
전체적으로 잘 구현해주셨네요.
간단한 피드백을 남겼으니, 확인해보세요~
질문이 있다면 언제든 코멘트와 LMS의 질문답변 페이지에 남겨주시면 빠르게 답변 드리겠습니다!

2022-09-20 13:47 UTC, ksy90101 commented on src/main/java/calculator/Application.java
> +        //TODO: 계산기 구현
이미 구현이 되었다면, 주석은 삭제하는것을 추천드립니다.

2022-09-20 13:47 UTC, ksy90101 commented on src/main/java/calculator/Application.java
> +        System.out.print(ans);
InputView에 대해선 잘 구현해주셨네요 👍 
Output도 결국 view가 아닐까요? 해당 부분도 view로 구현해보시면 좋을듯 하빈다.

2022-09-20 13:47 UTC, ksy90101 commented on src/main/java/calculator/Application.java
> +        double ans = stringCalculator.calculate(input);
축약어는 의미를 희석시키는 분제가 있습니다. 축약어 보단, 풀 네임을 작성하는게 어떠실까요?

2022-09-20 13:47 UTC, ksy90101 commented on src/main/java/calculator/domain/PostfixConvertor.java
> +    private static int idx = 0;
static으로 구현하면 어떤 단점이 있을까요?

2022-09-20 13:47 UTC, ksy90101 commented on src/main/java/calculator/domain/PostfixConvertor.java
> +        return;
마지막의 return은 작성 안해주셔도 괜찮습니다.

2022-09-20 13:47 UTC, ksy90101 commented on README.md
> +domain/PosfixConvertor => 중위표현식을 후위표현식으로 바꾸어주는 객체입니다.
👍

2022-09-20 13:47 UTC, ksy90101 commented on src/main/java/calculator/domain/Operator.java
> +        }
추상 메서드보단, 함수형 인터페이스와 람다를 이용해 구현해보시면 어떨까요?

2022-09-20 13:47 UTC, ksy90101 commented on src/main/java/calculator/domain/Operator.java
> +            if(operand2==0){
```suggestion
            if(operand2 == 0){
```

2022-09-20 13:47 UTC, ksy90101 commented on src/main/java/calculator/domain/Operator.java
> +    private final String textOperator;
symbol이라는 단어는 어떠신가요?

2022-09-20 13:47 UTC, ksy90101 commented on src/main/java/calculator/domain/Operator.java
> +    }
해당 부분을 stream의 findFirst() 메서드로 한번 구현해볼까요?

2022-09-20 13:47 UTC, ksy90101 commented on src/main/java/calculator/domain/PostfixConvertor.java
> +        while(!stack.isEmpty() && Operator.findOperator(stack.peek()).getPriority()>=Operator.findOperator(element).getPriority()){
한줄로 나열해서 읽는것 보단, 위에서 아래로 읽는것이 훨씬 더 잘 읽히는 케이스가 있습니다. 그래서 한줄의 점 하나라는 규칙이 있는데요. 한번 그 부분을 참고해서 해당 부분을 리팩토링 해보면 어떨까요? 또한, 이런식으로 긴 경우에는 변수로 따로 빼는게 더 가독성이 높을 수 있습니다.

2022-09-20 13:47 UTC, ksy90101 commented on src/main/java/calculator/domain/PostfixConvertor.java
> +}
개행도 의미를 전달하는 방법입니다.
의미없는 개행은 제거하면 어떨까요?

2022-09-20 13:47 UTC, ksy90101 commented on src/main/java/calculator/domain/StringCalculator.java
> +        return Double.parseDouble(stack.pop());
해당 부분은 현재 2depth인데요. 한번 1depth로 변경해볼까요? 대표적으론, 메소드 추출이 있을듯 합니다.

2022-09-20 13:47 UTC, ksy90101 commented on src/main/java/calculator/domain/StringCalculator.java
> +    private static Deque<String> stack = new ArrayDeque<>();
static은 동시성 이슈가 존재하는데요. 동시성 이슈를 방지하기 위해 final을 이용해 해당 필드의 상태를 변경할 수 없도록 합니다. 한번 알아보시면 좋을듯 합니다 :)

2022-09-20 16:20 UTC, SeokRae reviewed
안녕하세요. 지환님 !
피드백 받는 것도 학습의 일부입니다. !!

시험 보고 검사 받는다는 생각보다 작성할 때의 내 생각은 이렇다. 
의견 공유를 해달라는 식으로 가볍게 남겨주세요!

2022-09-20 16:20 UTC, SeokRae commented on README.md
> +
코드를 작성하신 후에 클래스의 역할을 작성하시는 것도 좋지만, 
TODO 리스트 작성하는 것처럼 요구사항을 적고 하나씩 체크하고, 코드를 작성하다보면 추가적으로 생기는 요구사항에 대해서도 점차 늘려가면서
설계하고 코드를 작성하실 때의 생각을 노출해주시면 더 좋습니다.

2022-09-20 16:20 UTC, SeokRae commented on src/main/java/calculator/Application.java
> +        String[] input = inputView.inputFormula();
사용자로부터 입력받은 값이라는 의미로 input도 이해는 되지만, 업무적으로 협업을 한다고 생각을 한다면 보다 명확한 의미를 갖는 변수명이 좋을 것 같습니다.

2022-09-20 16:20 UTC, SeokRae commented on src/main/java/calculator/domain/PostfixConvertor.java
> +    private static int idx = 0;
추가로 객체의 라이프 사이클에 대해서 한번 고민해보는 것도 좋을 것 같습니다.
객체가 생성될 때 변수의 scope나 어떤 메모리에 저장되는지도 그 범주 내의 개념에 있을 것 같습니다.

2022-09-21 12:37 UTC, JEONG-JIHWAN commented on src/main/java/calculator/Application.java
> +        System.out.print(ans);
ViewController를 만들어서 inputView 와 outputView를 구현했는데 괜찮은 방법인지 모르겠습니다....

2022-09-21 12:38 UTC, JEONG-JIHWAN commented on src/main/java/calculator/Application.java
> +        double ans = stringCalculator.calculate(input);
어떠한 변수명을 지을지 몰라서 input으로 했는데 고민해서 변경했습니다!

2022-09-21 12:41 UTC, JEONG-JIHWAN commented on src/main/java/calculator/domain/PostfixConvertor.java
> +    private static int idx = 0;
미리 메모리를 할당받기 때문에 의미없는 static 사용은 메모리 낭비될 가능성이 존재합니다.
한 스레드에서 값을 변경할 경우 다른 모든 스레드에서 영향을 받습니다. 이는 동시성 문제를 야기하게 됩니다.

2022-09-21 12:41 UTC, JEONG-JIHWAN commented on src/main/java/calculator/domain/PostfixConvertor.java
> +        return;
앗...... 삭제했습니다!

2022-09-21 12:43 UTC, JEONG-JIHWAN commented on src/main/java/calculator/domain/Operator.java
> +    }
stream으로 바꾸고 findFirst()로 바꾸었습니다. 근데 위의 코드에서 stream으로 바꾼게 어떠한 장점을 가지는지 잘 모르겠습니다 ㅜㅜ

2022-09-21 12:44 UTC, JEONG-JIHWAN commented on src/main/java/calculator/domain/PostfixConvertor.java
> +        while(!stack.isEmpty() && Operator.findOperator(stack.peek()).getPriority()>=Operator.findOperator(element).getPriority()){
객체지향 생활체조를 제대로 활용하지 못했네요 ㅜㅜ 바꾸었습니다!!

2022-09-21 12:44 UTC, JEONG-JIHWAN commented on src/main/java/calculator/domain/PostfixConvertor.java
> +}
네네 당장 제거하겠습니다

2022-09-21 12:45 UTC, JEONG-JIHWAN commented on src/main/java/calculator/domain/StringCalculator.java
> +        return Double.parseDouble(stack.pop());
메소드를 새로 만들어서 해결했습니다. 어느 부분까지 메서드를 해야할지는 항상 어려운것같습니다....

2022-09-21 12:46 UTC, JEONG-JIHWAN commented on src/main/java/calculator/domain/StringCalculator.java
> +    private static Deque<String> stack = new ArrayDeque<>();
네네 이부분에 대해서 추가로 공부해보겠습니다.

2022-09-21 12:50 UTC, JEONG-JIHWAN commented on src/main/java/calculator/Application.java
> +        String[] input = inputView.inputFormula();
네네!! 변수명에 좀더 주의를 기울일게요...!!

2022-09-21 12:53 UTC, JEONG-JIHWAN commented on src/main/java/calculator/domain/PostfixConvertor.java
> +    private static int idx = 0;
무분별한 static을 남용하는것같아 고민이 많았는데 해당 내용 공부하면서 다시 고민해보겠습니다. 감사합니다!

2022-09-22 10:57 UTC, ksy90101 commented on src/main/java/calculator/domain/PostfixConvertor.java
> +    private static int idx = 0;
네. 동시성 문제를 해결 하기 위해 final을 붙여 동시성 문제를 해결하곤 합니다.
지금과 같은 경우엔 final을 붙일순 없겟죠.
따라서 해당 부분을 리팩토링 해보시면 좋을듯 해요.

2022-09-22 10:58 UTC, ksy90101 commented on src/main/java/calculator/domain/Operator.java
> +    }
차후에 enum에 하나더 추가가 되었을때 (예를들면 루트를 계산하는게 추가되었다고 해봅시다. 그렇다면 해당 부분에 if문을 작성하지 않아도 enum값만 추가할수 있지 않을까요?

2022-09-22 11:25 UTC, ksy90101 approved these changes
안녕하세요 :) 지환님. 이번에는 간단한 클린코드에 대한 피드백들을 위주로 남겨드렸습니다.
1단계 미션은 이만 머지해도 될듯 합니다.
추가 코드리뷰는 2단계때 진행해주시면 좋을듯 합니다. 2단계 미션때 추가적으로 피드백 수정해주신 부분들도 전체적으로 확인하도록 하겠습니다.
2단계때 테스트 코드 작성도 파이팅입니다!

2022-09-22 11:25 UTC, ksy90101 commented on src/main/java/calculator/domain/OperatorService.java
> +        .get();
null이 나오면 NPE가 발생할 확률이 높습니다. 이런 경우엔 NPE보단, error를 발생시키게 하는 것이 더 좋을듯 합니다.

아울러 이 부분은 Service보단, 해당 클래스(Operator)에 있는게 더 어울린듯 합니다.

2022-09-22 11:25 UTC, ksy90101 commented on src/main/java/calculator/domain/StringCalculator.java
> +}
이 부분의 개행도 역시, 의미를 나타내지 않는다면 제거해주세요.

2022-09-22 11:26 UTC, merged