[1기][최준아] 문자열 계산기 과제
programmers-lecture/java-calculator pull request #6
Opened 2022-09-20 23:14 UTC by joona95

일찍 해서 제출하고 싶었는데 일이 많이 생겨서 급히 하게 돼서 너무 슬프네요. 🥲
아래에 과제 진행하면서 생각하거나 궁금한 점 정리해봤습니다.
- 객체지향 생활 체조 총정리에서 한 메서드에 depth를 하나만 주라고 해서 for문 안에서 if 확인하는 걸 메서드 분리를 했는데 이렇게 진행하는 게 맞을지 잘 모르겠어요. 아니면 더 좋은 분리 방법이 있을까요? (참고 커밋: 메서드 depth 줄이기)
- 처음엔 한 메서드에서 스택이나 리스트를 지역변수로 사용했는데, depth를 줄이기 위해서 메서드를 분리하게 되면 클래스 인스턴스 변수로 사용하게 되는데 이로 인한 문제는 없을까요?
- 함수 이름 짓는 게 항상 너무 어렵네요 ..
- PostfixConvertor 클래스의 addOperatorInPostfixFormula 메서드의 depth를 줄일 방법이 있을까요? 메서드 분리를 이 이상 어떤 단위(의미)로 나눠야 할지 잘 모르겠어요.
- Stream을 사용해서 더 효율적으로 사용할 수 있는 부분이 있을까요? 사용하고 싶었는데 막상 하려다보니 익숙하지 않아서인지 활용을 못한 것 같아요.

2022-09-21 12:26 UTC, SeokRae reviewed
안녕하세요. 준아님!
열심히 커밋 하셨군요.! 고생하셨습니다.

평가 받는 자리가 아니라 의견 공유하는 자리인 만큼 이것저것 생각을 말씀해주시면 좋을 것 같습니다.
자그마한 피드백 남기겠습니다.!

![CleanShot 2022-09-21 at 20 36 16](https://user-images.githubusercontent.com/17922700/191494237-bcf79cf4-1b1b-45a9-9d1a-67729186985c.png)

2022-09-21 12:26 UTC, SeokRae commented on src/main/java/caculator/enums/Operator.java
> +    public Integer getPriority() {
사용되지 않는 메서드입니다.!

2022-09-21 12:26 UTC, SeokRae commented on src/main/java/caculator/enums/Operator.java
> +    }
```suggestion
    public boolean isSameOperator(String operator) {
        return Arrays.stream(values())
	        .anyMatch(op -> op.operator.equals(operator));
    }
```

이 메서드를 Util에서 가져가서 로직을 만드는데, enum 내에서 구현해도 되지 않을까 싶습니다.
boolean 값을 반환하는 anyMatch를 사용하게 되면, 위에서 제안해 드렸던 연산자 수정 또는 추가 시
enum 내에서 연산자만 추가하면 그에 따른 로직이 알아서 처리될 듯합니다.

2022-09-21 12:26 UTC, SeokRae commented on src/main/java/caculator/models/Calculator.java
> +    private Stack<Double> numbers = new Stack<>();
자료구조를 사용할 때는 고민이 많이 필요합니다.
Stack 클래스는 우리가 알고 있는 알고리즘의 Stack과는 조금 다릅니다. 
Stack 클래스를 보면 Deque인터페이스를 선언, ArrayDeque 구현체를 초기화 하여 사용하길 권장합니다.

![CleanShot 2022-09-21 at 21 14 44](https://user-images.githubusercontent.com/17922700/191501062-f7a14711-dab8-449f-9a61-10f64f136a61.png)

Stack은 Vector를 상속 받아서 사용하고 있기 때문에 의도와는 벗어난 api가 노출이 되어 문제가 생길 가능성이 높습니다.

![CleanShot 2022-09-21 at 21 18 53](https://user-images.githubusercontent.com/17922700/191501838-4c0069a1-7cc8-42ce-a0e3-d0b764e348f4.png)

참고해볼만한 링크 공유합니다.
- [Java의 Stack 대신 Deque](https://tecoble.techcourse.co.kr/post/2021-05-10-stack-vs-deque/)

2022-09-21 12:26 UTC, SeokRae commented on src/main/java/caculator/utils/Util.java
> +    public static boolean isOperator(String operator) {
꼭 필요한 메서드인지 고민이 되는 부분입니다.

2022-09-21 12:26 UTC, SeokRae commented on src/main/java/caculator/models/PostfixConvertor.java
> +    private List<String> postfixFormula = new Stack<>();
List 인터페이스를 선언하고 Stack을 구현해야 하는 이유가 궁금합니다.!

2022-09-21 12:44 UTC, SeokRae commented
> * 객체지향 생활 체조 총정리에서 한 메서드에 depth를 하나만 주라고 해서 for문 안에서 if 확인하는 걸 메서드 분리를 했는데 이렇게 진행하는 게 맞을지 잘 모르겠어요. 아니면 더 좋은 분리 방법이 있을까요? (참고 커밋: 메서드 depth 줄이기)

depth의 깊이를 깊게 가져야면 안되는 이유부터 생각해보아야 할 것 같습니다. 
depth를 낮게 가져갈 수록 얻을 수 있는 부분은 depth를 줄이기 위해 메서드를 강제로 분리하게끔 유도한다는 것입니다.
그런 목표가 있기 때문에 강제로 그러한 제약을 걸고 해보는것이 좋다고 생각합니다.

> * 처음엔 한 메서드에서 스택이나 리스트를 지역변수로 사용했는데, depth를 줄이기 위해서 메서드를 분리하게 되면 클래스 인스턴스 변수로 사용하게 되는데 괜찮은가요?

depth를 줄이기 위해 지역 변수를 줄일 수 밖에 없었고, 인스턴스 변수로 선언했다면.. 고민해봐야 할 것 같습니다. 매개 변수로 넘기는 방법으로는 안되었을까요?

> * 함수 이름 짓는 게 항상 너무 어렵네요 ..

ㅋㅋ 맞습니다!!

![image](https://user-images.githubusercontent.com/17922700/191506007-008c9a57-0ad4-4a93-901f-9094d57179ad.png)


> * PostfixConvertor 클래스의 addOperatorInPostfixFormula 메서드의 depth를 줄일 방법이 있을까요? 메서드 분리를 이 이상 어떤 단위(의미)로 나눠야 할지 잘 모르겠어요.

알고리즘 적인 부분은 커멘트 해드리기가 쉽지 않습니다.! 

> * Stream을 사용해서 더 효율적으로 사용할 수 있는 부분이 있을까요? 사용하고 싶었는데 막상 하려다보니 익숙하지 않아서인지 활용을 못한 것 
같아요.

stream을 꼭 사용해야 한다는 것은 아닙니다. 하지만 반복문이 들어가는 부분에 대해서는 모두 사용할 수 있습니다.
연산처리가 되는 부분에 대해서 고민해보시는 것이 좋을 듯합니다.

2022-09-21 13:00 UTC, joona95 commented on src/main/java/caculator/enums/Operator.java
> +    public Integer getPriority() {
앗 getter 제거 커밋에서 getOperator 메서드 제거하면서 이것도 같이 지웠다고 생각했는데 빼먹었네요 🥲 지우겠습니다!

2022-09-21 13:01 UTC, joona95 commented on src/main/java/caculator/models/PostfixConvertor.java
> +    private List<String> postfixFormula = new Stack<>();
앗.. 일부러 이유가 있어서 stack으로 사용한 게 아니에요.. `new ArrayList<>();` 로 하려 했는데 자동완성 쓰다가 잘못 들어갔던 것 같습니다 🥲 수정하겠습니다..!

2022-09-22 11:32 UTC, joona95 commented on src/main/java/caculator/controller/CalculatorController.java
> +public class CalculatorController {
딱히 이유가 있어서라기보다 view와 model 이어주는 controller 역할을 하는 객체를 만들어야겠다고 생각하고 관성적으로 네이밍했던 것 같아요.
음 그럼 입력 받고 후위표기식 변경 후 계산하고 출력하는 전 과정을 맡고 있는 객체이니 CalculatorProgram/CalculationProgram같은게 더 나을까요?

2022-09-22 11:33 UTC, joona95 commented on src/main/java/caculator/controller/CalculatorController.java
> +    public static void calculatorRun() {
아 그렇겠네요. 기본생성자가 public이라 그렇게 하는 편이 좋을 것 같네요. 수정하겠습니다.

2022-09-22 11:34 UTC, ksy90101 requested changes
안녕하세요 준아님 :)
전체적으로 잘 구현해주셨네요 💯 
알이 이미 많은 부분들을 리뷰를 주셔서, 추가적인 리뷰는 많이 없습니다.
한번 전체적으로 보시고 수정해보시면 좋을듯 합니다.

질문이 있다면 언제든 LMS의 질문답변 게시판을 이용해주세요!

2022-09-22 11:34 UTC, ksy90101 commented on src/main/java/caculator/models/Calculator.java
> +            throw new RuntimeException("올바르지 않은 계산식입니다.");
RuntimeException 보단, 의미이는 예외를 한번 사용해보시면 좋을거 같습니다.

2022-09-22 11:34 UTC, ksy90101 commented on src/main/java/caculator/models/Calculator.java
> +        if(numbers.size() != 1)
이러한 매직넘버는 어떤걸 의미하는지는 이 코드를 처음 보는 분들은 햇갈릴수 있습니다.
매직넘버를 제거해볼까요?

2022-09-22 11:34 UTC, ksy90101 commented on src/main/java/caculator/views/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
static은 어떤 문제점이 있을까요?

동시성 이슈가 있을수 잇는데, 동시성 이슈를 해결하기 위한 방법을 한번 고민해보세요.

2022-09-22 11:34 UTC, ksy90101 commented on src/main/java/caculator/views/OutputView.java
> +public class OutputView {
static 메서드만 제공했을 경우엔, 생성자 생성을 막는것이 좋습니다.
https://github.com/Meet-Coder-Study/book-effective-java/blob/main/2%EC%9E%A5/4_%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4%ED%99%94%EB%A5%BC_%EB%A7%89%EC%9C%BC%EB%A0%A4%EA%B1%B0%EB%93%A0_private_%EC%83%9D%EC%84%B1%EC%9E%90%EB%A5%BC_%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC_%EA%B9%80%EA%B4%91%ED%9B%88.md

해당 링크를 한번 참고해보세요.

2022-09-22 11:34 UTC, ksy90101 commented on src/main/java/caculator/models/PostfixConvertor.java
> +            }
이 부분은 3depth가 되고 있네요.
depth가 깊어질수록, 코드의 복잡성은 높아지며, 각 부분들이 어떤걸 의미하는지 알기가 어렵습니다.
한번 이 부분을 어떻게 개선할 수 있을지 고민해보세요.

대표적으로 변수와 메서드 분리가 있을듯 합니다.

2022-09-22 11:42 UTC, joona95 commented on src/main/java/caculator/enums/Operator.java
> +    }
오 넵 확실히 저렇게 표현하니 이후 수정이 편리할 것 같네요..!

2022-09-22 11:45 UTC, joona95 commented on src/main/java/caculator/enums/Operator.java
> +    }
넵 enum 내부에서 처리하는 편이 나을 것 같습니다! 수정하겠습니다!

2022-09-22 11:49 UTC, joona95 commented on src/main/java/caculator/models/Calculator.java
> +            throw new RuntimeException("올바르지 않은 계산식입니다.");
넵 그러면 자바 예외를 좀 더 살펴보겠습니다. IllegerArgumentException 같은 예외를 사용하면 더 좋겠네요!

2022-09-22 11:50 UTC, joona95 commented on src/main/java/caculator/models/Calculator.java
> +        if(numbers.size() != 1)
아하 넵 상수 처리하도록 하겠습니다.

2022-09-22 11:53 UTC, ksy90101 commented
1.객체지향 생활 체조 총정리에서 한 메서드에 depth를 하나만 주라고 해서 for문 안에서 if 확인하는 걸 메서드 분리를 했는데 이렇게 진행하는 게 맞을지 잘 모르겠어요. 아니면 더 좋은 분리 방법이 있을까요? (참고 커밋: 메서드 depth 줄이기)
- 대부분 메서드를 이용해 depth를 줄이고 있습니다. depth가 깊어지면, 코드의 복잡성이 올라가고, 코드가 의미하는 바를 희석시키는 부분이 있습니다. 또한, 변수명을 이용하는 케이스도 있습니다. 아울러 책임과 역할을 생각해 원시값 포장하거나, 객체를 만들어서 처리하기도 합니다.

2.. 처음엔 한 메서드에서 스택이나 리스트를 지역변수로 사용했는데, depth를 줄이기 위해서 메서드를 분리하게 되면 클래스 인스턴스 변수로 사용하게 되는데 괜찮은가요?
- 스택이나 리스트가 한번 객체의 상태이여야 하는지 고민해보세요. depth를 줄이기 위해 인스턴스 변수를 사용하는것은 안좋은 방식입니다.

3. 함수 이름 짓는 게 항상 너무 어렵네요 ..
참 어려운 일이죠. ㅠㅠ 개인적으론 길어저도 괜찮으니 의미를 전달하는데 너무 제약을 두진 마세요!

5. PostfixConvertor 클래스의 addOperatorInPostfixFormula 메서드의 depth를 줄일 방법이 있을까요? 메서드 분리를 이 이상 어떤 단위(의미)로 나눠야 할지 잘 모르겠어요.
해당 부분은 알이 리뷰에 잘 남겨주신듯 합니다.

7.Stream을 사용해서 더 효율적으로 사용할 수 있는 부분이 있을까요? 사용하고 싶었는데 막상 하려다보니 익숙하지 않아서인지 활용을 못한 것 같아요.

개인적으론 지금도 충분히 잘 사용해주셨습니다 💯 계속해서 스트림을 사용하려고 노력한다면 익숙해지는듯 합니다.

2022-09-26 11:13 UTC, joona95 commented on src/main/java/caculator/controller/CalculatorController.java
> +public class CalculatorController {
https://github.com/programmers-lecture/java-calculator/pull/6/commits/aed4c49ff7b2b7f796f1d8ef890705602bddfc8e
문자열계산기 전체 실행 부분이라고 생각해서 TextCalculator 로 변경했습니다.

2022-09-26 11:13 UTC, joona95 commented on src/main/java/caculator/controller/CalculatorController.java
> +    public static void calculatorRun() {
https://github.com/programmers-lecture/java-calculator/pull/6/commits/c4247d332b2a504b7290ab0b9aeeed1169c871c7
static 메서드만 제공 시 private 생성자로 작성하였습니다.

2022-09-26 11:14 UTC, joona95 commented on src/main/java/caculator/views/OutputView.java
> +public class OutputView {
https://github.com/programmers-lecture/java-calculator/pull/6/commits/c4247d332b2a504b7290ab0b9aeeed1169c871c7
static 메서드만 제공 시 private로 생성자 제한했습니다.

2022-09-26 11:15 UTC, joona95 commented on src/main/java/caculator/enums/Operator.java
> +    }
https://github.com/programmers-lecture/java-calculator/pull/6/commits/a7baed38dac5a2f61e8af302b905ad6bd03c40b9
stream 사용하여 수정하면서 enum 내부에서 처리하도록 했습니다.

2022-09-26 11:15 UTC, joona95 commented on src/main/java/caculator/utils/Util.java
> +    public static boolean isOperator(String operator) {
https://github.com/programmers-lecture/java-calculator/pull/6/commits/a7baed38dac5a2f61e8af302b905ad6bd03c40b9
stream 사용하여 enum 내부에서 처리하도록 수정했습니다.

2022-09-26 11:16 UTC, joona95 commented on src/main/java/caculator/enums/Operator.java
> +    Operator(String operator, Integer priority, BiFunction<Double, Double, Double> expression) {
https://github.com/programmers-lecture/java-calculator/pull/6/commits/4f7983ef080e1af2a3cb20003bbfe643eba4fc0b
이렇게 BiFunction을 BinaryOperator 로 변경하였습니다. 이부분에 대한 수정 말씀하신 게 맞을까요?

2022-09-26 11:17 UTC, joona95 commented on src/main/java/caculator/enums/Operator.java
> +    }
https://github.com/programmers-lecture/java-calculator/pull/6/commits/a7baed38dac5a2f61e8af302b905ad6bd03c40b9
stream 사용하여 처리하도록 수정했습니다.

2022-09-26 11:17 UTC, joona95 commented on src/main/java/caculator/enums/Operator.java
> +    public Integer getPriority() {
https://github.com/programmers-lecture/java-calculator/pull/6/commits/c53be8470603db53fec1753965d5142f2436f6ec
해당부분 제거했습니다.

2022-09-26 11:18 UTC, joona95 commented on src/main/java/caculator/models/Calculator.java
> +    private Stack<Double> numbers = new Stack<>();
https://github.com/programmers-lecture/java-calculator/pull/6/commits/eb92a83262c692d7dd91f17e27b83ab69280cf44
네 이해했습니다! 해당 부분 더 알맞은 자료구조로 변경했습니다.

2022-09-26 11:18 UTC, joona95 commented on src/main/java/caculator/views/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
https://github.com/programmers-lecture/java-calculator/pull/6/commits/68d5db30ac3ae0aec677883e46af6640792440ba
해당부분 메서드 안에서 선언하여 해결했습니다.

2022-09-26 11:20 UTC, joona95 commented on src/main/java/caculator/models/Calculator.java
> +            throw new RuntimeException("올바르지 않은 계산식입니다.");
https://github.com/programmers-lecture/java-calculator/pull/6/commits/7dfa6f096554ce03cf63943d6a4eb3f763a197f8
전체적으로 exception을 일으키는 경우가 계산 공식 입력이 잘못들어와서 생긴 케이스라고 생각해서 IllegerArgumentException으로 변경하였습니다.

2022-09-26 11:20 UTC, joona95 commented on src/main/java/caculator/models/Calculator.java
> +        if(numbers.size() != 1)
https://github.com/programmers-lecture/java-calculator/pull/6/commits/05cdfddbfcecd4f9b5ae180312908bcc7c2a3573
상수처리해보았습니다.

2022-09-26 11:21 UTC, joona95 commented on src/main/java/caculator/models/PostfixConvertor.java
> +            }
https://github.com/programmers-lecture/java-calculator/pull/6/commits/bf53db7a184c7fcde696a934ecdb147b5e97c70a
고민해보다가 메서드 분리로 depth 줄여보았습니다.

2022-09-26 14:14 UTC, merged