[1기][김선호] 문자열 계산기 과제
programmers-lecture/java-calculator pull request #7
Opened 2022-09-21 13:10 UTC by preferKim

기초가 부족한 걸 많이 느꼈고, 아는 문법 이리저리 조합해가면서 무지성으로 작성해봤습니다..🤣🤣 🤣
현재 모르는 것이 무엇인지도 모르는 답없는 실력이지만, 리뷰해주시는 것들 차근차근 단계별로 적용해보면서 꾸준히 고치고 흡수해나가겠습니다. 많은 지도편달 부탁드립니다!!!

2022-09-22 11:44 UTC, ksy90101 requested changes
안녕하세요 :) 선호님. 마르코입니다.
미션 구현하시느라 너무 고생 많으셨습니다!!
간단한 피드백을 남겼으니, 확인해주시면 좋을거 같습니다.
언제든 질문이 있다면 코멘트나 LMS 질문답변을 이용해 남겨주시면 답변드리겠습니다~

2022-09-22 11:44 UTC, ksy90101 commented on .gitignore
> +src/main/java/Test.java
해당 부분을 gitignore에 넣어두신 이유가 무엇인가요?

2022-09-22 11:44 UTC, ksy90101 commented on README.md
> +- [ ] 나눗셈의 몫이 0인 경우에 대한 예외처리
이 부분은 처리가 안된걸까요?

2022-09-22 11:44 UTC, ksy90101 commented on README.md
> +### 필수 요구사항
👍

2022-09-22 11:44 UTC, ksy90101 commented on src/main/java/CalculatorApp.java
> +public class CalculatorApp {
항상 모든 class는 패키지에 묶여잇는거 훨씬 좋습니다.
한번 패키지에 묶어보세요.

2022-09-22 11:44 UTC, ksy90101 commented on src/main/java/DataHandler.java
> +        Stack<String> stack = new Stack<>();
stack이 두개일 이유가 있나요? 하나로 처리가 가능할듯 한데요.
아울러 Stack보단, Deque를 사용하는것이 훨씬 좋습니다.

[Java 의 Stack 대신 Deque - Tecoble](https://tecoble.techcourse.co.kr/post/2021-05-10-stack-vs-deque/)
한번 위에 글을 참고해보세요.

2022-09-22 11:44 UTC, ksy90101 commented on src/main/java/view/InputView.java
> +    private boolean isExitOrder(String inputString) {
해당 메서드는 사용하지 않는듯 하네요.?

2022-09-22 11:44 UTC, ksy90101 commented on src/main/java/Operator.java
> +    protected final String OPERATOR;
상수가 아닌 경우엔, 대문자로 작성하는것 보단 카멜케이스를 이용하는게 좋습니다.

2022-09-22 11:44 UTC, ksy90101 commented on src/main/java/view/OutputView.java
> +        System.out.printf("결과는 %d\n", result);
`\n`보단, System.lineSeparator()를 사용하는것이 좋습니다.

이유는, 개행은 각 OS마다 다르게 가져가는데, 이 메서드가 그걸 모두다 지원하고 있습니다.

2022-09-22 11:44 UTC, ksy90101 commented on src/main/java/view/OutputView.java
> +    static final String EXIT_MESSAGE = "프로그램을 종료합니다...";
default 메서드를 이용하신 이유가 있나요>

2022-09-22 11:44 UTC, ksy90101 commented on src/main/java/Calculator.java
> +        System.out.println("문자열 계산기 프로그램을 실행합니다... ('0'을 입력하여 종료)");
이 부분도 View일꺼 같네요.

2022-09-22 11:44 UTC, ksy90101 commented on src/main/java/Calculator.java
> +            // 입력
주석들은 작성을 하지 않는것이 좋습니다.
그 이유는 주석을 작성하지 않아도 코드로만 의미를 나타내는것이 훨씬 더 깔끔한 케이스가 되는거 같습니다.

2022-09-22 11:44 UTC, ksy90101 commented on src/main/java/DataHandler.java
> +    private static HashMap<String, Integer> priorityMap = new HashMap<>();
static만 사용하면 어떤 단점이 있을까요?

2022-09-22 11:44 UTC, ksy90101 commented on src/main/java/DataHandler.java
> +        priorityMap.put("/", 2);
이미   enum을 통해 symbol을 구현해두신듯 한데, enum을 키값으로 써보시면 어떨까요?
EnumMap이라는 것도 존재하기 때문에, 한번 알아보시면 좋을거 같습니다.

2022-09-22 11:44 UTC, ksy90101 commented on src/main/java/DataHandler.java
> +    public DataHandler(String inputString) {
자바는 타입이 있기 떄문에 굳이, 변수를 이용해 String이라는것을 나타낼 필요는 없습니다.

2022-09-22 11:44 UTC, ksy90101 commented on src/main/java/DataHandler.java
> +        priorityMap.put("/", 2);
이 클래스가 생성될때마다, 계속 해당 부분을 put을 하게 될꺼 같아요. static이기 때문에 계속 생성될거 같고 이런 경우엔 어떻게 할 수 있을까요?
static 메서드를 사용하면 되지 않을까요?

2022-09-22 11:44 UTC, ksy90101 commented on src/main/java/Operator.java
> +        }
익명 클래스보단, 함수형 인터페이스를 사용하는것을 추천드립니다.
한번 함수형 인터페이스에 대해 알아보시면 좋을거 같습니다.

2022-09-22 11:44 UTC, ksy90101 commented on src/main/java/Operator.java
> +            return operand1 / operand2;
operand2가 0이면, 예외가 터질듯 합니다. 한번 이부분도 고려해볼까요?

2022-09-22 15:06 UTC, preferKim commented on .gitignore
> +src/main/java/Test.java
간단하게 문법 연습을 하기 위한 테스트 용도였습니다. 테스트코드를 적용함으로써 불필요한 파일의 생성을 방지하겠습니다!

2022-09-22 15:20 UTC, preferKim commented on src/main/java/CalculatorApp.java
> +public class CalculatorApp {
`main 메서드`를 포함하는, 시작을 위한 `Application 클래스` 또한 패키지로 관리하라는 말씀이시군요. domain 패키지에 속하는 것은 아닌 것 같고, application 패키지(?) 로 관리해도 무방할까요?

2022-09-23 20:16 UTC, preferKim commented on src/main/java/Operator.java
> +    protected final String OPERATOR;
final 이면 무조건 상수라고 잘못이해하고 있었네요😅 수정해보겠습니다!

2022-09-24 02:29 UTC, preferKim commented on src/main/java/Operator.java
> +            return operand1 / operand2;
https://github.com/preferKim/java-calculator/blob/bcf67803b8d7aa366f3cdab169478988ed4ed0b1/src/main/java/domain/Operator.java#L22-L30

일단 예외처리를 했는데, 예외가 발생하고 나서도 계속 프로그램이 실행되게 하기 위한 처리는 하지 못한 상태입니다. 예외처리를 계속 공부해보면서 어떻게 만져야할지 고민해보겠습니다. 제가 구현한 코드에서 try catch 문으로 나누는 게 더 좋은 판단이었을 지 조언해주시면 감사하겠습니다!

2022-09-24 02:47 UTC, preferKim commented on src/main/java/DataHandler.java
> +        priorityMap.put("/", 2);
https://github.com/programmers-lecture/java-calculator/pull/7#discussion_r979141729

해당 부분을 기본 생성자에 포함시키고 Priority를 사용하는 클래스에서는 private final로 인스턴스를 생성하여 관리해봤습니다. static 메서드로 구현하면 어쨌든 이 Map을 초기화 해주기 위해서 최소 한 번은 호출해주어야 할 것이고, 그래서 딱 한 번만 인스턴스를 생성함으로써 기본 생성자를 통해 Map이 초기화되게끔 구현하였습니다. 확인해주시면 감사하겠습니다😆

2022-09-24 02:51 UTC, preferKim commented on src/main/java/CalculatorApp.java
> +public class CalculatorApp {
https://github.com/preferKim/java-calculator/tree/preferKim/src/main/java 

MVC를 공부해보고 해당 패턴에 맞는 폴더 구조로 변경했습니다. 도메인에는 데이터에 관련된 클래스가 들어간다고 이해해서 Operator Enum클래스를 도메인으로 넣었습니다. 또, 모든 클래스는 패키지에 들어있는게 좋으므로 main()메서드를 포함하는 클래스는 일단 contoller 패키지에 넣었는데, 새로 application 패키지로 빼는 게 나았을지 궁금합니다. 조언해주시면 감사하겠습니다 :)

2022-09-24 03:00 UTC, preferKim commented on src/main/java/DataHandler.java
> +        Stack<String> stack = new Stack<>();
https://github.com/preferKim/java-calculator/blob/bcf67803b8d7aa366f3cdab169478988ed4ed0b1/src/main/java/service/Calculator.java#L12-L20

Stack구현체가 가지는 단점(성능 저하, 다중 상속을 지원하지 않음)을 알아보고 Deque 를 ArrayDeque 구현체로 구현하였습니다. 여기서 고민이 생겼습니다. 저는 stack 관련된 기능만 쓰기로 계획했는데, 그럼 네이밍을 deque라고 할지 stack이라고 할지 고민하다가 일단 stack으로 네이밍했습니다. 또, 메서드를 `push(), poll()` 와 `addFirst(), pollFirst()`  중 무엇을 사용할까 고민하다가 `아 이 놈은 이름은 stack이지만 ArrayDeque로 구현된거야` 라고 알게 하기위해 후자를 선택했습니다. 이러한 사고 흐름이 바람직한지 의견을 구하고 싶습니다. 또, 실제로 현업에서도 이런 류의 고민을 하시는지 궁금합니다(이런 경우 역시 기업별로 컨벤션을 정해두었을 것 같긴 합니다😅)

2022-09-24 03:09 UTC, preferKim commented on src/main/java/DataHandler.java
> +        priorityMap.put("/", 2);
https://github.com/preferKim/java-calculator/blob/bcf67803b8d7aa366f3cdab169478988ed4ed0b1/src/main/java/service/Priority.java#L7-L22

EnumMap을 이용하여 구현한 연산자 우선순위와 연산자 우선순위를 구하는 메서드입니다.  여기서는 제가 임의로 우선순위를 Integer 타입으로 지정해버렸는데, 이를 Java 내부에서 처리할 수 없었는지 고민됩니다. 원래는 Enum 클래스 내에서 `compareTo()` 를 사용하여 연산순위를 구하는 로직을 짜볼까 했는데, Map을 사용하는 것이 더 직관적인 것 같아 이렇게 구현하였습니다.

2022-09-24 03:12 UTC, preferKim commented on src/main/java/view/InputView.java
> +    private boolean isExitOrder(String inputString) {
커밋하기 전에 사용하지 않는 메서드가 없는지 확인하는 습관을 들이도록 하겠습니다! 더불어 Ctrl + Alt + O 단축키를 자주 사용하여 사용하지 않는 import문 또한 제거하도록 연습하겠습니다!

2022-09-24 03:14 UTC, preferKim commented on src/main/java/view/OutputView.java
> +        System.out.printf("결과는 %d\n", result);
https://github.com/preferKim/java-calculator/blob/bcf67803b8d7aa366f3cdab169478988ed4ed0b1/src/main/java/view/OutputView.java#L10-L12

OS마다 다를 거라고는 생각해보지 않았던 부분입니다. JVM을 통해 자바가 OS에 독립적이다 정도만 알고 있었던 상태였습니다.😅 더 안정적으로 프로그램을 개발할 수 있는 인사이트를 주셔서 감사합니다 :)

2022-09-24 03:16 UTC, preferKim commented on src/main/java/view/OutputView.java
> +    static final String EXIT_MESSAGE = "프로그램을 종료합니다...";
사실 접근 제어자에 크게 고민하지 않았던 것 같습니다. 클래스, 변수, 메서드 모두 사용범위에 따라 접근 제어자를 타이트하게 달 수 있도록 고민하겠습니다.

2022-09-24 03:21 UTC, preferKim commented on src/main/java/Calculator.java
> +        System.out.println("문자열 계산기 프로그램을 실행합니다... ('0'을 입력하여 종료)");
https://github.com/preferKim/java-calculator/blob/preferKim/src/main/java/view/InputView.java

사실 아직 객체지향의 책임과 협력 이러한 개념들을 숙지하지 못해 중구난방으로 작성했던 것 같습니다. 역할과 책임 키워드를 찾아보고 InputView에서 종료조건 또한 검증하도록 수정해봤습니다. 
PS) 이런식으로 객체지향 개념을 하나씩 녹여내가면서 코드를 짜게 될 수 있을 거란 기대감에 많이 설레는 중입니다.😁

2022-09-24 03:22 UTC, preferKim commented on src/main/java/Calculator.java
> +            // 입력
TODO 주석만 남기고는 모든 주석을 삭제했습니다. 주석이 없어도 코드만으로 의미와 목적이 분명한 코드가 될 수 있게 연습해보겠습니다.

2022-09-24 03:32 UTC, preferKim commented on src/main/java/DataHandler.java
> +    private static HashMap<String, Integer> priorityMap = new HashMap<>();
1. 프로그램과 라이프사이클을 같이합니다. 가비지 컬렉터에 의해 제거되지도 않으므로, 메모리 누수가 일어날 수 있습니다.
2. static필드는 모든 스레드에서 공유합니다. 따라서 한 스레드에서 값이 변경되는 경우 다른 스레드도 영향을 받으므로 이는 동시성 문제를 야기할 수 있습니다. (동시성 이슈에 관해서는 추후 더 공부해보겠습니다.)

이 외에도, 외부에서 필드에 접근할 수 없다는 캡슐화 원칙을 지키기 위해서는 static만 사용하는 것이 아닌 static final을 사용하면 될 것 같습니다.  여담으로 멘토님께서는 static을 언제 사용한다라는 본인만의 기준 혹은 컨벤션 등이 있는 지 궁금합니다.

2022-09-24 03:34 UTC, preferKim commented on src/main/java/DataHandler.java
> +    public DataHandler(String inputString) {
프로그램을 갈아엎으면서, 변수명을 대폭 수정하였습니다. 변수명을 어떻게 지으면 잘 지었다고 소문이 날 지, 명명론에 대해서 추가적으로 공부해보겠습니다.

2022-09-24 07:47 UTC, SeokRae commented on src/main/java/CalculatorApp.java
> +public class CalculatorApp {
자바에서 패키지가 의미하는 바에 대해서 확인이 필요할 것 같습니다.
패키지라는 것은 하나의 프로젝트를 구성하는 클래스들을 성격별로 의도적으로 나누어 관리하는 기능 입니다.

프로그램이 MVC라는 패턴으로 관리할 수 있도록 구성하였다면, 그것 또한 맞다고 생각합니다.
여기서 요지는 프로젝트를 만들 때 자신만의 패키지 체계를 유지하는 것입니다.

- [자바 패키지](https://wikidocs.net/231)

2022-09-24 08:00 UTC, SeokRae commented on src/main/java/DataHandler.java
> +        Stack<String> stack = new Stack<>();
의도하신 내용을 정리하면 
결론적으로 Stack을 사용한 것은 아니고 Deque의 API를 사용하셨으나 변수명을 stack으로 사용하셨다. 인 것 같습니다.

협업하는 사람이 코드롤 보고 이를 수정해야 한다면, stack이라는 변수명을 보고 Stack의 매커니즘을 떠올렸을 것 같은데 실상으로는 Deque의 API가 떠서 당황할 것 같습니다.

이러한 경우에 해결책은 Deque<String> stack = new ArrayDeque<>(); 를 필드로 갖는 클래스를 별도로 구성하고, 현재 로직에서 필요한 API만 재구성하여 커스텀한 자료구조를 만들 것 같습니다.

2022-09-26 14:15 UTC, merged