[1기][박현서] 문자열 계산기 테스트 코드 과제
programmers-lecture/java-calculator pull request #9
Opened 2022-10-02 07:58 UTC by hyena0608

안녕하세요 😊
문자열 계산기 테스트 코드 작성해봤습니다 !

테스트 코드를 작성하면서 느끼고 배운 점이 많았습니다.

## 느낀 점, 배운 점
### 1.  JUnit5, AssertJ 이용기
ParameterizedTest의 속성으로 테스트명과 DisplayName의 각 테스트명을 
작성하여 `어떤 주제의 테스트`에서 `어떤 부분`에서 성공, 실패했는지 판단할 수 있었습니다.
MethodSource를 이용해서 테스트 데이터를 분리하여 코드가 보기 편해졌으며
또한  AssertJ 라이브러리를 이용하여 assertThat에 메서드 체인을 이용하니 JUnit5의 assertEqual보다 더 직관적인 테스팅이 가능했습니다.
계속해서 연습해온 람다, 스트림도 테스트 코드를 작성하면서 큰 도움이 되었습니다.

### 2. 테스트 하기 좋은 메서드
지금까지 자바 애플리케이션을 구현하면서 설계가 잘못되었는지 판단하기 어려웠던 부분이 있었습니다.
이번에 테스트 코드를 작성하다 보니 다음과 같은 것을 느낄 수 있었습니다.
	- 현재 클래스에서 테스트할 동작이 아니다.
	- 현재 클래스에서 테스트가 필요한데 해당 메서드를 못불러온다.

> 이를 해결하기 위해 테스트 코드를 작성하니 
> `getter`, `setter`, `property` 를 작성하거나
>  `private`을 `public`으로 변경해야 하는 등 
> `데이터나 동작을 노출하게 되는 일이 일어났고 이것이 결국 설계의 문제임을 파악할 수 있었습니다.`

전에 세션에서 다른 분께서 질문하신 private은 어떻게 테스팅하는가에 대해서 질문이 있었고
그에 강사님의 답변이 생각나면서 많은 생각을 해볼 수 있었습니다.

실제로 이번 문자열 계산기에 테스트 코드를 작성하면서 
어떤 클래스 다른 역할을 하는 것을 보고 수정할 수 있었으며 테스트 코드의 또 다른 중요성도 알게 되었습니다.

---

## 강사님께 질문 할 것
### 1. 테스트 데이터 작성
테스트 데이터를 작성하다 보니 코드가 읽기 어려워졌습니다.
주로 MethodSource를 이용해 데이터를 테스트 밑에 빼놨는데
이 `데이터용 메서드를 따로 테스트 디렉터리 내에 클래스로 작성하는 것은 괜찮은 방법인지 궁금합니다.`

저는 직관적인 테스트를 작성하려고 노력했고
- 테스트 메서드명 
	- void whenXXXThenXXX
	- @ParameterizedTest(name = “[{index}] XXX”)
	- @MethodSource(“getXXXWhenXXXThenXXX”)
	- @DisplayName(“XXX”)
- 메서드 참조, 람다
- AssertJ
를 이용했습니다.

하지만 각 테스트 중간중간에 있는
테스트 데이터용 메서드가 있는데 이 부분에서 테스트 코드를 읽기가 어려워지는 거 같다는 느낌을 받았습니다.
각 테스트에 필요한 데이터를 메서드 밑에 작성함으로서 
`어떤 데이터가 들어가는지 곧바로 파악하기는 좋지만 너무 많은 데이터는 오히려 다른 테스트 코드를 보는데 어려웠습니다.`
때문에 테스트 데이터용 클래스를 따로 작성하는 것이 어떤지 생각하게 됐습니다 !

감사합니다 😁

2022-10-03 10:59 UTC, SeokRae commented
> ### 1. 테스트 데이터 작성
> 테스트 데이터를 작성하다 보니 코드가 읽기 어려워졌습니다. 주로 MethodSource를 이용해 데이터를 테스트 밑에 빼놨는데 이 `데이터용 메서드를 따로 테스트 디렉터리 내에 클래스로 작성하는 것은 괜찮은 방법인지 궁금합니다.`

말씀하신 내용을 test fixture라고해서 "테스트 실행을 위해 사용되는 모든 것"에 대한 개념이 존재합니다. 이를 관리하는 방법으로 테스트 패키지에 공통적인 더미 데이터를 관리하기도 합니다. 라이브 세션에서 보여드린 코드의 경우 한 화면 안에서 보여드리기 위해서 하나의 클래스 내에서 작성되었음을 전달드립니다.

2022-10-03 10:59 UTC, SeokRae commented
> ### 1. 테스트 데이터 작성
> 테스트 데이터를 작성하다 보니 코드가 읽기 어려워졌습니다. 주로 MethodSource를 이용해 데이터를 테스트 밑에 빼놨는데 이 `데이터용 메서드를 따로 테스트 디렉터리 내에 클래스로 작성하는 것은 괜찮은 방법인지 궁금합니다.`

말씀하신 내용을 test fixture라고해서 "테스트 실행을 위해 사용되는 모든 것"에 대한 개념이 존재합니다. 이를 관리하는 방법으로 테스트 패키지에 공통적인 더미 데이터를 관리하기도 합니다. 라이브 세션에서 보여드린 코드의 경우 한 화면 안에서 보여드리기 위해서 하나의 클래스 내에서 작성되었음을 전달드립니다.

2022-10-03 11:00 UTC, SeokRae commented
> ### 1. 테스트 데이터 작성
> 테스트 데이터를 작성하다 보니 코드가 읽기 어려워졌습니다. 주로 MethodSource를 이용해 데이터를 테스트 밑에 빼놨는데 이 `데이터용 메서드를 따로 테스트 디렉터리 내에 클래스로 작성하는 것은 괜찮은 방법인지 궁금합니다.`

말씀하신 내용을 test fixture라고해서 "테스트 실행을 위해 사용되는 모든 것"에 대한 개념이 존재합니다. 이를 관리하는 방법으로 테스트 패키지에 공통적인 더미 데이터를 관리하기도 합니다. 라이브 세션에서 보여드린 코드의 경우 한 화면 안에서 보여드리기 위해서 하나의 클래스 내에서 작성되었음을 전달드립니다.

2022-10-06 11:57 UTC, ksy90101 commented on src/main/java/stringcalculator/exception/ExceptionBody.java
> +    public ExceptionBody(ExceptionEnum exceptionType) {
이거 말곤 이 클래스는 하나도 안쓰이는듯 한데, 어느 경우에 쓰이는건가요?

2022-10-06 11:58 UTC, ksy90101 commented on src/main/java/stringcalculator/exception/ExceptionEnum.java
> +        throw new RuntimeException(getErrorMessage(exceptionType));
runtimeException보단, 더 명시적인 이름의 예외를 사용하는것이 좋을듯 합니다.

2022-10-06 11:58 UTC, ksy90101 commented on src/main/java/stringcalculator/exception/ExceptionEnum.java
> +import java.util.Optional;
이것들은 안쓰이네요!

2022-10-06 11:58 UTC, ksy90101 commented on src/main/java/stringcalculator/converter/FormConverter.java
> +            new ExceptionBody(FORMULA_NULL_ERROR);
```suggestion
            throw new ExceptionBody(FORMULA_NULL_ERROR);
```

2022-10-06 11:59 UTC, ksy90101 commented on src/main/java/stringcalculator/converter/FormConverter.java
> +                .find();
```suggestion
        return Pattern.compile("^[!@#$%^&_=|\\\\`~,.<>?;:'\"A-z{}\\[\\]]$")
                .matcher(inputForm)
                .find();
```
한줄에 점 하나씩으로 메서드 체이닝을 하면 더 가독성이 높아집니다.

2022-10-06 11:59 UTC, ksy90101 commented on src/main/java/stringcalculator/converter/FormConverter.java
> +        return formula.equals("(") || formula.equals(")");
매직스트링은 없애는게 좋을듯 해요.

2022-10-06 12:00 UTC, ksy90101 commented on src/main/java/stringcalculator/converter/FormConverter.java
> +                .find();
Pattern은 비싼 객체입니다.
https://developer-hm.tistory.com/99
상수화를 해서 캐싱해볼까요~?

2022-10-06 12:00 UTC, ksy90101 commented on src/main/java/stringcalculator/converter/PostfixConverter.java
> +        ArrayDeque<String> operatorDeque = new ArrayDeque<>(formulas.size());
구현체보단, 인터페이스를 타입으로 지정하는게 더 좋을듯 해요!

2022-10-06 12:00 UTC, ksy90101 commented on src/main/java/stringcalculator/MainApplication.java
> +import stringcalculator.view.Reader;
여기에 있는것들도 안쓰이네요.

2022-10-06 12:00 UTC, ksy90101 commented on src/main/java/stringcalculator/operator/Operator.java
> +import stringcalculator.exception.ExceptionEnum;
여기도 안쓰이네요!

2022-10-06 12:01 UTC, ksy90101 commented on src/main/java/stringcalculator/view/Reader.java
> +public class Reader {
static 클래스는 기본생성자를 사용하지 못하도록 생성자를 막아두면 어떨까요?

2022-10-06 12:01 UTC, ksy90101 commented on src/main/java/stringcalculator/view/Reader.java
> +    private static boolean checkInputFormOk(String inputForm) {
이 메서드는 안쓰이는듯 하네요?

2022-10-06 12:19 UTC, ksy90101 commented on src/main/java/stringcalculator/operator/Operator.java
> +            throw new IllegalArgumentException(DIVIDE_ZERO_ERROR.getDesc());
이부분을 DEVIDE의 simpleCacultor 로직으로 넣으면 어떨까요?
모든 계산이 이 로직을 탈 필요가 없어보여서요.

2022-10-06 12:19 UTC, ksy90101 commented on src/main/java/stringcalculator/operator/Operator.java
> +                .parallel()
parallel을 쓰신 이유가 따로 잇나요?

2022-10-06 12:19 UTC, ksy90101 commented on src/main/java/stringcalculator/operator/Operator.java
> +                .findAny();
FindAny와 FindFirst를 한번 알아볼까요?

2022-10-06 12:20 UTC, ksy90101 requested changes
꼼꼼한 테스트 코드가 인상깊었습니다 💯 
간단한 피드백을 남겼으니, 한번 확인해주시면 감사하겠습니다!

2022-10-06 12:21 UTC, ksy90101 commented
컨플릭트가 너무 많이 나네요? 뭔가 다른 이유가 있는걸까요?

2022-10-07 16:15 UTC, hyena0608 commented on src/main/java/stringcalculator/exception/ExceptionBody.java
> +    public ExceptionBody(ExceptionEnum exceptionType) {
처음에 사용자 정의 예외를 따로 만들어 좀 더 명시적인 예외를 만들어야겠다고 생각했고
RuntimeException을 상속 받아놨었습니다.
이후에 사용자 정의 예외를 ExceptionEnum에서 관리하려고 했습니다.
ExceptionEnum을 작성하고 시도하던 중에 생각처럼 쉽지 않아서 RuntimeException으로 던지고 그 상태로 유지 됐습니다.

처음으로 문자열 계산기를 작성하면서 예외처리에 대해서 생각해보고 구현하면서 생각처럼 잘 되지 않았습니다 ㅎㅎ..
지금은 ExceptionBody 클래스를 지우고 예외 메시지 관리 전략으로 변경했습니다 !

2022-10-07 16:15 UTC, hyena0608 commented on src/main/java/stringcalculator/exception/ExceptionEnum.java
> +        throw new RuntimeException(getErrorMessage(exceptionType));
지금은 ExceptionMessage를 통해서 통합 예외 메시지 관리를 하는 방식으로 재수정했습니다 !

2022-10-07 16:18 UTC, hyena0608 commented on src/main/java/stringcalculator/operator/Operator.java
> +            throw new IllegalArgumentException(DIVIDE_ZERO_ERROR.getDesc());
말씀해주신것처럼 모든 연산이 저 로직을 무조건적으로 돌게 되는데
실제 로직이 필요한 부분은 나누기(DIVIDE) 부분이기에
simpleCalculator 로직 안으로 수정했습니다 !

2022-10-08 01:54 UTC, ksy90101 commented on src/main/java/stringcalculator/exception/ExceptionBody.java
> +    public ExceptionBody(ExceptionEnum exceptionType) {
넵 좋습니다 👍 
너무 어려운 방식을 사용하기 보단, 단순한 방법이 어떨땐, 가장 관리하기가 좋을때가 많습니다!!

2022-10-29 23:57 UTC, closed without merging